### ISSUE TITLE
googlesheets4 not in CRAN

### ISSUE THREAD

**Issue by ianformanek** [tidyverse/googlesheets4#10]
The install instructions suggest that a released version is available in CRAN, but that does not seem to be the case: https://cran.r-project.org/package=googlesheets4 => 404

```
> install.packages("googlesheets4")
Warning message:
package 'googlesheets4' is not available (for R version 3.2.3)
```

It might be that the 
```
## NO, NO YOU CANNOT
```
comment is meant to document this, but it did not do it for me. Would not hurt to be more explicit (or remove the line `You can install the released version of googlesheets4 from CRAN with:`)

**Comment by renekyewski** [comment]
+1

**Comment by katiedrax** [comment]
+1

**Comment by jennybc** [comment]
This will be true soon: #34
