### ISSUE TITLE
sheets_append function missing

### ISSUE THREAD

**Issue by RSherwoodJr** [tidyverse/googlesheets4#104]
The documentation shows a function [sheets_append(data, ss, sheet = 1)](https://googlesheets4.tidyverse.org/reference/sheets_append.html) but this function doesn't seem to exist in the package.

`Error in sheets_append(...  : 
  could not find function "sheets_append"`

**Comment by jennybc** [comment]
It is only in the dev version. Install from GitHub.

**Comment by RSherwoodJr** [comment]
Thanks!

**Comment by jennybc** [comment]
Sorry for any confusion, but having a release and dev version of the website also ends up confusing people, so for such a new package I generally don't go there.

**Comment by RSherwoodJr** [comment]
No need to apologize at all--your work has made my quantified self data
organizing so much easier!

**Comment by RSherwoodJr** [comment]
It appears this issue is present in the dev release, now.  I have it installed from github, but am getting 

```
Error in sheets_append(df, ss = "abcdefg",  : 
  could not find function "sheets_append"
```

Tried reinstalling the dev version, and it says:
```
> devtools::install_github("tidyverse/googlesheets4")
Skipping install of 'googlesheets4' from a github remote, the SHA1 (89ebac74) has not changed since last install.
  Use `force = TRUE` to force installation
```

So I uninstalled the package and reinstalled it and am seeing the same "could not find function" error.

**Comment by jennybc** [comment]
@RSherwoodJr The function is called `sheet_append()`. `sheet` with no "s".

https://googlesheets4.tidyverse.org/reference/sheet_append.html

**Comment by RSherwoodJr** [comment]
Such a minor change in the code with such a big impact. lol  Had been running that script weekly since February when you had me download the dev version, and wasn't sure why it stopped working.  Thanks!

**Comment by jennybc** [comment]
There was A Great Renaming upon the release of v0.2.0:

https://googlesheets4.tidyverse.org/news/index.html#function-naming-scheme 

The addition of creating / writing / editing functions necessitated rethinking the naming scheme.
