### ISSUE TITLE
How to create spreadsheet in the folder

### ISSUE THREAD

**Issue by selesnow** [tidyverse/googlesheets4#111]
Hi Jenny, thank for googlesheets4.

`sheets_create()`  does't have `folder` or `parent` argument. Can you implemente this to `sheets_create()` ?

**Comment by jennybc** [comment]
Unfortunately there is no way to do this with the Sheets API. It requires the Drive API. So your current solution is to use googlesheets4 and googledrive together and basically do it yourself:

https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html

There are (at least 2) workflows today:

  * Initiate the Sheet in the desired folder with `googledrive::drive_upload()` or `drive_create()`. Then do downstream spreadsheet work via googlesheets4.
  * Initiate the Sheet with `googlesheets4::sheets_create()` and, at your earliest convenience, use `googledriv::drive_mv()` to put the Sheet into the desired folder.

I can imagine greater integration between googlesheets4 and googledrive in the future. If I create a way for people to opt in to "googledrive-y flavored googlesheets4", then I could make certain workflows more pleasant. But we're not there yet and my current priority is making sure googlesheets4 (+ googledrive) is a complete replacement for (old) googlesheets before March 1.
