### ISSUE TITLE
Feature request: set column width

### ISSUE THREAD

**Issue by peeter-t2** [tidyverse/googlesheets4#112]
Any plans to allow setting column width through R? It'd be a very useful feature, if google spreadsheets are used to create a manual annotation workflow for a number of coders, but columns are not even size.

Even setting width to autofit would be great support. Thanks! (Great package btw, using dev version to write easily)

**Comment by jennybc** [comment]
No immediate plans. The immediate priority is to make sure all features of (old) googlesheets are implemented. And googlesheets really didn't support writing formats.

But I think we will get there in the future.

**Comment by peeter-t2** [comment]
Cool! Thanks for the quick response and good luck with the current plans!

**Comment by jennybc** [comment]
Actually I think I will make "auto-width-izing" of columns part of what we do when we write a table, such as in `sheets_write()`.

https://developers.google.com/sheets/api/samples/rowcolumn#automatically_resize_a_column

**Comment by peeter-t2** [comment]
Wow, that would be great!

I wonder if it's already in the API, is there a way that this could be used already?
Thanks, best!

**Comment by peeter-t2** [comment]
Works perfectly! Wow, this was quick!!! Thanks!

Btw, I would suggest to make it maybe default but optional. I can also imagine situations where lots of content in one cell might make this undesirable. But maybe this is where the opinionated approach comes in that it's a bad idea to make these cells.

**Comment by jennybc** [comment]
Yeah I know someone will immediately request more control 😁.

`sheets_write()` is meant to be opinionated and simple and do the right thing for 80% of data frames. I don't want it to gain a bunch of fiddly arguments. There are other ways to just write data and some folks will need to use them. I will also create a helper soon for keeners who are motivated enough to craft some of these formatting adjustments themselves.

**Comment by peeter-t2** [comment]
Yep, makes sense! Good luck again! :)

**Comment by jennybc** [comment]
I changed my mind again and no longer do this automatically.

There's a new function `sheets_auto_resize_dims()` that exposes this on-demand.

**Comment by peeter-t2** [comment]
Ok. Thanks for letting me know!
