### ISSUE TITLE
read_sheet adds backslash

### ISSUE THREAD

**Issue by ahelgason** [tidyverse/googlesheets4#115]
Hi,

I have a cell in Google Sheets that has a backslash:

A very long \n title

However, when I import the sheet into R, another backslash is added. 

A very long \\n title

Is there a way to suppress the addition of the backslash?

Cheers,
Agnar

```r

mre <- read_sheet("https://docs.google.com/spreadsheets/d/152hkR1isG98Hk83Zgc8Xio3J3_9P2cZ2jOyES7CCKss/edit?usp=sharing")

mre

```

**Comment by jennybc** [comment]
You're seeing normal escaping of special characters. No extra backslash has been added, by googlesheets4 or R.

``` r
library(googlesheets4)
sheets_deauth()

url <- "https://docs.google.com/spreadsheets/d/152hkR1isG98Hk83Zgc8Xio3J3_9P2cZ2jOyES7CCKss/edit?usp=sharing"
mre <- read_sheet(url, col_names = FALSE)
#> Reading from "Untitled spreadsheet"
#> Range "Sheet1"
#> New names:
#> * `` -> ...1
mre$...1[1]
#> [1] "A very long \\n title"
writeLines(mre$...1[1])
#> A very long \n title

local_string <- "I contain \\n a newline"
local_string
#> [1] "I contain \\n a newline"
writeLines(local_string)
#> I contain \n a newline
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Helpful reading in R for Data Science re: strings:

https://r4ds.had.co.nz/strings.html#string-basics

**Comment by ahelgason** [comment]
Thank you for your quick response, Jenny.

Basically, I don't want the backslash to be escaped normally, since the string is a label and I want the label to include a line break. I would expect that typing in an identical string in Sheets and R ("A very long \n title") would result in the same behavior on a graph. However, while the latter (correctly) has a line break, the former types out "\n" with no line break. So it seems as if somewhere a backslash is added going from Sheets to R. See below:

```
library(ggplot2)
library(googlesheets4)
sheets_deauth()
mre <- read_sheet("https://docs.google.com/spreadsheets/d/152hkR1isG98Hk83Zgc8Xio3J3_9P2cZ2jOyES7CCKss/edit?usp=sharing")

ggplot(mre,aes(x=var, y=value))+geom_col()

mre$string= "A very long \n title"
ggplot(mre,aes(x=string, y=value))+geom_col()

```
Apologies in advance if I'm just being dense about this.

**Comment by jennybc** [comment]
Well, I was too glib about where this is coming from. It's from the transit via JSON, which is how the Sheets API sends (and receives) data.

Here is me reading your sheet just using curl in the shell (via a tool that Google offers), so there is no R, jsonlite, httr, or googlesheets4 involved. And you'll see that the newline is already escaped there. I think you will just have to plan accordingly in terms of how you use character strings that have been read from a Sheet.

``` bash
curl \
  'https://sheets.googleapis.com/v4/spreadsheets/152hkR1isG98Hk83Zgc8Xio3J3_9P2cZ2jOyES7CCKss/values/Sheet1?key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed

```

Here's the response:
``` json
{
  "range": "Sheet1!A1:Z1000",
  "majorDimension": "ROWS",
  "values": [
    [
      "var",
      "value"
    ],
    [
      "A very long \\n title",
      "5"
    ]
  ]
}
```

**Comment by jennybc** [comment]
More abstract, unsolicited advice: I would try to handle this sort of detail (where to put a line break in a piece of text on a plot) as close to "plot time" as possible and in the most abstract way as possible. So maybe you can rethink the workflow and use the Sheet for just _data_ and deal with line breaking / line wrapping on the R side?

**Comment by jennybc** [comment]
Alternative suggestion from @Hadley: put an actual newline in the cell.

I've done that in this Sheet:
https://docs.google.com/spreadsheets/d/1Mb28E_NL5lyW6lDGCyNtRv05mLyKvFTsvmz3vFVfxwE/edit?usp=sharing

``` r
library(ggplot2)
library(googlesheets4)
sheets_deauth()

jenny_sheet_id <- "1Mb28E_NL5lyW6lDGCyNtRv05mLyKvFTsvmz3vFVfxwE"
mre <- read_sheet(jenny_sheet_id)
#> Reading from "newline-study"
#> Range "Sheet1"
mre
#> # A tibble: 1 x 2
#>   var                  value
#>   <chr>                <dbl>
#> 1 "A very long\ntitle"     5

ggplot(mre,aes(x=var, y=value))+geom_col()
```

![](https://i.imgur.com/cGEBdTm.png)

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by ahelgason** [comment]
How wonderfully simple!  Thank you for taking the time to resolve this for me.

Regarding workflow: I realize it's preferable to manipulate labels as close to plotting as possible (and I would do that in my own work). However, I'm teaching a course on data literacy and visualization for students with a high level of stats anxiety, so I rely mostly on Sheets, but then switch to R/ggplot for viz. I'm basically testing the limits of how far I can get with doing things on the Sheets side (remarkably far, so far). For myself or for more quantitatively oriented students, I'd of course do everything through R/tidyverse.

**Comment by jennybc** [comment]
So then putting an actual line break in the cell seems really natural.
