### ISSUE TITLE
Single quote (escape) being added to text fields starting with =

### ISSUE THREAD

**Issue by j-Rinehart** [tidyverse/googlesheets4#116]
First off, thanks for building and maintaining this (and previous) packages.  I use them all the time, and they really are a vital part of my daily workflow.

Now my question: 

I have a df where the first column is a link to a publicly available image.  I prepare each field in that column for inserting into a Google Sheet so they have the format: `=image("http//IMAGE_URL.com")`

I have inserted like this via googledrive using `drive_upload()` with no issues.  It writes that column as is, and the resulting Google Sheet links to, and displays the image in the corresponding cell.  

In googlesheets4, I have tried a few insertion methods: (1) directly inserting using `sheets_create()`, and (2) inserting into an existing sheet using `sheets_write()`.  Both methods insert the df correctly, but add a single (escape) quote before the equal sign in that column.  That results in the cells showing the formula above rather than linking to and showing the image.  

Is there an option to prevent that from occurring?

**Comment by jennybc** [comment]
> Is there an option to prevent that from occurring?

Yes I believe I know what needs to happen. I need to somehow know that such a value is not a regular character string, but is rather a *formula*. And then I write the `CellData` differently. Specifically, I write `userEnteredValue` as a `formulaValue` as opposed to a `stringValue`.

I need to think about how to expose this, but it will presumably require attaching some sort of class or attribute to the column that needs this treatment.

**Comment by j-Rinehart** [comment]
Would it be possible to detect that by seeing if the first character in any string was `=`?  If so...likely a formula, and could be noted as such as it passes through to the API.

**Comment by jennybc** [comment]
No I think I need to provide an S3 class for people to use that indicates a character vector contains formulas.

**Comment by j-Rinehart** [comment]
OK...let me know if I can be of any assistance.  In the interim, I think I have found a clunky way of fixing things post import so it shows the image link (or any formula, really) if anyone finds their way here with a similar issue and needs a band-aid solution.

**Comment by obarisk** [comment]
If the **formular** cells all located in some columns of a dataframe,
could there be another argument(vector) like ``raw_col=c(1, 2)`` for sheets_write, sheets_append, sheets_edit, which use **raw** for ValueInputOption.

**Comment by JMKelleher** [comment]
Hi @j-Rinehart , would you mind sharing the band-aid solution you found for this issue?

**Comment by jennybc** [comment]
FWIW I will have a real solution to this soon and it will definitely be in before the near-term CRAN release.

**Comment by j-Rinehart** [comment]
Sounds like Jenny is on this (Thanks, Jenny!), but my band-aid in GSheets is as follows:

- Highlight the column with the formulas
- Go to Data > 'Split text to columns'
- A little window pops up -> click 'Custom'
- Enter in the single (escape) quote in the box > hit return
(this should have removed the leading quote, but still doesn't fully fix the problem)
- Re-select the column and click Edit > Find & Replace
- Replace `=` with `=` (literally replacing the equal sign with another equal sign)

That should do it!
