### ISSUE TITLE
write_sheet and sheets_write not found in namespace

### ISSUE THREAD

**Issue by wildcat47** [tidyverse/googlesheets4#129]
I have a basic issue - am I missing something obvious? Has write functionality been discontinued?

Error: 'sheets_write' is not an exported object from 'namespace:googlesheets4'

```r
library(tidyverse)
library(googlesheets4)
df = data.frame(x=1:10)
ss = read_sheet("https://docs.google.com/spreadsheets/d/1w5XCmd3cDnxD3aWBDTtzmzrqCTAbhnquVu7TTA3zkEY/edit#gid=0")
df %>% googlesheets4::sheets_write(ss, sheet='forecast')
```

**Comment by jennybc** [comment]
The writing functions aren't in the CRAN version. They are currently available only in the dev version that you'd install from GitHub.
