### ISSUE TITLE
Sheets Append Not Included in googlesheets 4

### ISSUE THREAD

**Issue by dcaley5005** [tidyverse/googlesheets4#134]
```r
I installed googlesheets4 and can't find the sheets_append package.  
Tidyverse website [here](https://googlesheets4.tidyverse.org/) shows that it exists.  
Installed the package directly from googlesheets4 github and function exists, 
but multiple packages are needed and can't be installed on R 3.6.  

I feel like the bug here is not code related but consistency in documentation.  
Please clear up my misconception.  I am new to R and could be speaking off base.  
Thank you for all the hard work on this package.

```

**Comment by jennybc** [comment]
`sheets_append()` and, indeed, all writing functionality is currently only in the dev version. So, yes, you will have to install from GitHub to get that right now. You should be able to do so as explained here:

https://googlesheets4.tidyverse.org/#installation

Note that there was a problem with the macOS part of CRAN recently, which may have been part of your struggle? I.e. there was a time when one could not install from CRAN on macOS. But that has been resolved now, at the source. It can take a little while to propagate to all the CRAN mirrors.

A CRAN release will happen soon.
