### ISSUE TITLE
No sheets_write(), sheets_create() etc. under CentOS

### ISSUE THREAD

**Issue by untergeekDE** [tidyverse/googlesheets4#135]
Hi Jenny, let me start by thanking you for your tremendous work, which gives people like me, with limited coding abilities, access to very powerful tools (I am a data journalist by trade). And forgive me for misusing Github as a forum. 

My problem is that I can't find all the writing functions in an installation on a CentOS Linux server: sheets_write() and sheets_create() are not available in the package, although they work well on my Windows machine. 

Installed the gargle package and the googlesheets4 package from Github using devtools, so I have the version 4_0.2 on the CentOS version (while the version on my Windows machine is 4_0.1). Still no sheets_write(), sheets_create(). Things like sheets_read() on the same ss are running fine. 

What am I missing?

**Comment by AndrewMarritt** [comment]
I'm having the same issue but on a Mac. Tried installing from CRAN and then from Github.

**Comment by jennybc** [comment]
> so I have the version 4_0.2 on the CentOS version (while the version on my Windows machine is 4_0.1)

I'm not sure what to make of this as the current version of googlesheets4 looks nothing like this. It's  0.2.0.9000. Can you show me live R code with commands like `library(googlesheets4)` and `packageVersion("googlesheets4")` and `searchpaths()`?

The write functions aren't in the CRAN version yet.

All of the above sounds like failure to install from GitHub or failure to load the version installed from GitHub.

**Comment by AndrewMarritt** [comment]
Just revisited my issue. It is as you suggest a failure to install from Github:

`Error: Failed to install 'googlesheets4' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES'`

**Comment by jennybc** [comment]
Yeah CRAN broke the macOS index this week. It is now fixed but in the same way that the breakage took a while to propagate to mirrors, so is the fix.

You could experiment with your CRAN mirror, trying to get a "good one". Or wait. Or install from GitHub, but you might experience the same CRAN problem with other packages.

**Comment by jennybc** [comment]
@AndrewMarritt re: this

> converted from warning

This also suggests you might want to back off on this for the moment. Are you perhaps setting `options(warn = 2)` in `.Rprofile` or something?

**Comment by AndrewMarritt** [comment]
Hi Jenny

I've taken the view to wait until the fix propogates following your advice earlier.

The only thing in my `.Rprofile` is

`options(spacy_condaenv = "spacy_condaenv")`

which I suspect won't be causing any issues in this case.

**Comment by jennybc** [comment]
If `install.packages()` and `install_github()` are still balky, you can grab the source and install from that too.

**Comment by untergeekDE** [comment]
Misread the sessionInfo() output ("googlesheets4_0.1.0.9000"), excuse me. 

I tried again, and the sheets_write() function is there now. So maybe all I had to do was to restart the R session. 

Erm, thanks...
