### ISSUE TITLE
read_sheet() periodically fails on same sheet

### ISSUE THREAD

**Issue by behrman** [tidyverse/googlesheets4#136]
We have a script that tries to read this Google sheet every hour

[https://docs.google.com/spreadsheets/d/1CLwPasPsM24_l2beFfyO-wYKDAbNdaASP90bRGphuwE/edit#gid=731625094](https://docs.google.com/spreadsheets/d/1CLwPasPsM24_l2beFfyO-wYKDAbNdaASP90bRGphuwE/edit#gid=731625094)

A couple times a day the read fails. The `read_sheet()` is inside a `tryCatch()`, and the object it assigns to is never created. What could be causing this, and is there anything we can do to avoid this failure to read?

**Comment by jennybc** [comment]
I can't find that text ("Null message body; hope that's ok") anywhere in googlesheets4, gargle, httr, or curl. (Nor did I expect to.) So I conclude it must be originating with Google, although I'm also not entirely sure how it would get fed through into this message.

If I google "Null message body; hope that's ok", I do get hits that make me suspect you might have some ?bash? scripts on your end? And maybe this is about _that_ and not about googlesheets4 at all?

**Comment by behrman** [comment]
Thanks, Jenny. You're right. We have the `read_sheet()` within a `tryCatch()`. In case of an error, the script sends us an email with an empty message body, hence the error message. Still the read is periodically failing with the same code running every hour. Is there anything we can do to avoid this?

**Comment by jennybc** [comment]
If you saw the failure directly, it should come with lots of information about the error. With this much indirection, it's going to be very hard to debug.

**Comment by behrman** [comment]
I believe our log file captures everything that `read_sheet()` prints out. It did capture

    Reading from "COVID-19 cases"
    Range "'California'"

but nothing else. It simply failed to assign the result. Is there a way we can get more verbose comments, or a debugging mode, or a way we can make use of the condition argument that `tryCatch()` sends the error function?

**Comment by jennybc** [comment]
Hopefully this snippet helps. Here I am trying to read a nonexistent Sheet ID.

``` r
library(googlesheets4)

sheets_deauth()

x <- tryCatch(
  read_sheet("12345"), 
  gargle_error_request_failed = function(e) e
)
class(x)
#> [1] "gargle_error_request_failed" "rlang_error"                
#> [3] "error"                       "condition"

str(x, max.level = 1)
#> List of 4
#>  $ message: chr "Client error: (404) NOT_FOUND\n  * A specified resource is not found, or the request is rejected by undisclosed"| __truncated__
#>  $ trace  :List of 4
#>   ..- attr(*, "class")= chr "rlang_trace"
#>  $ parent : NULL
#>  $ resp   :List of 10
#>   ..- attr(*, "class")= chr "response"
#>  - attr(*, "class")= chr [1:4] "gargle_error_request_failed" "rlang_error" "error" "condition"

# better for interactive use
#x$message

# better for capturing with reprex
cat(x$message, sep = "\n")
#> Client error: (404) NOT_FOUND
#>   * A specified resource is not found, or the request is rejected by undisclosed reasons, such as whitelisting.
#>   * Requested entity was not found.
#> Backtrace:
#>      █
#>   1. ├─base::tryCatch(read_sheet("12345"), gargle_error_request_failed = function(e) e)
#>   2. │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
#>   3. │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   4. │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
#>   5. └─googlesheets4::read_sheet("12345")
#>   6.   └─googlesheets4:::get_cells(...) /Users/jenny/rrr/googlesheets4/R/sheets_read.R:99:2
#>   7.     └─googlesheets4::sheets_get(ssid) /Users/jenny/rrr/googlesheets4/R/get_cells.R:20:2
#>   8.       └─googlesheets4:::sheets_get_impl_(as_sheets_id(ss)) /Users/jenny/rrr/googlesheets4/R/sheets_get.R:21:2
#>   9.         └─gargle::response_process(raw_resp) /Users/jenny/rrr/googlesheets4/R/sheets_get.R:38:2
#>  10.           └─gargle:::stop_request_failed(error_message(resp), resp) /Users/jenny/rrr/gargle/R/response_process.R:77:4

str(x$resp, max.level = 1)
#> List of 10
#>  $ url        : chr "https://sheets.googleapis.com/v4/spreadsheets/12345?fields=spreadsheetId%2Cproperties%2CspreadsheetUrl%2Csheets"| __truncated__
#>  $ status_code: int 404
#>  $ headers    :List of 12
#>   ..- attr(*, "class")= chr [1:2] "insensitive" "list"
#>  $ all_headers:List of 1
#>  $ cookies    :'data.frame': 0 obs. of  7 variables:
#>  $ content    : raw [1:114] 7b 0a 20 20 ...
#>  $ date       : POSIXct[1:1], format: "2020-03-27 21:50:26"
#>  $ times      : Named num [1:6] 0 0.00161 0.02453 0.09564 0.19709 ...
#>   ..- attr(*, "names")= chr [1:6] "redirect" "namelookup" "connect" "pretransfer" ...
#>  $ request    :List of 7
#>   ..- attr(*, "class")= chr "request"
#>  $ handle     :Class 'curl_handle' <externalptr> 
#>  - attr(*, "class")= chr "response"
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by behrman** [comment]
I used this code

```r
  sheet_last <-
    tryCatch(
      sheet_id %>%
        read_sheet(
          sheet = regions[[region]]$name,
          col_types = "cii"
        ) %>%
        top_n(1, update),
      error = function(condition) {
        system(str_glue(error_sheet_read))
      }
    )
  if (!is_tibble(sheet_last)) {
    class(sheet_last)
    str(sheet_last, max.level = 1)
    cat(sheet_last$message, sep = "\n")
    str(sheet_last$resp, max.level = 1)
    return()
  }
```

and got this

     int 0
    Error: $ operator is invalid for atomic vectors

Does this give you any insights?

**Comment by jennybc** [comment]
Perhas you are capturing the error that comes from passing bad input to `top_n()`.

I would isolate the `read_sheet()` call inside the `tryCatch()` and use an `error` condition more like mine (that just passes the captured error). If you've gotten an error, write it to an `.rds` file for post mortem inspection. Otherwise, proceed with `top_n()` and the rest of the analysis.

**Comment by behrman** [comment]
Thanks for the explanation. I now understand your example code and modified my code to

```r
  x <-
    tryCatch(
      sheet_id %>%
        read_sheet(sheet = regions[[region]]$name),
      error = function(e) {
        system(str_glue(error_sheet_read))
        e
      }
    )
  str(x, max.level = 1)
  cat(x$message, sep = "\n")
  str(x$resp, max.level = 1)
```

The code tries to read in different worksheets from the same spreadsheet. I'm getting two different types of error. First, the 503

```r
List of 4
 $ message: 'glue' chr "Server error: (503) UNAVAILABLE\n  * Service unavailable. Typically the server is down.\n  * The service is cur"| __truncated__
 $ trace  :List of 4
  ..- attr(*, "class")= chr "rlang_trace"
 $ parent : NULL
 $ resp   :List of 10
  ..- attr(*, "class")= chr "response"
 - attr(*, "class")= chr [1:4] "gargle_error_request_failed" "rlang_error" "error" "condition"
Server error: (503) UNAVAILABLE
  * Service unavailable. Typically the server is down.
  * The service is currently unavailable.
List of 10
 $ url        : chr "https://sheets.googleapis.com/v4/spreadsheets/1CLwPasPsM24_l2beFfyO-wYKDAbNdaASP90bRGphuwE?ranges=%27San%20Mate"| __truncated__
 $ status_code: int 503
 $ headers    :List of 12
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 $ all_headers:List of 1
 $ cookies    :'data.frame':	0 obs. of  7 variables:
 $ content    : raw [1:122] 7b 0a 20 20 ...
 $ date       : POSIXct[1:1], format: "2020-04-02 21:21:27"
 $ times      : Named num [1:6] 0.00 3.50e-05 3.70e-05 9.90e-05 1.85e+02 ...
  ..- attr(*, "names")= chr [1:6] "redirect" "namelookup" "connect" "pretransfer" ...
 $ request    :List of 7
  ..- attr(*, "class")= chr "request"
 $ handle     :Class 'curl_handle' <externalptr> 
 - attr(*, "class")= chr "response"
```

And second the 500

```r
List of 4
 $ message: 'glue' chr "Server error: (500) INTERNAL\n  * Internal server error. Typically a server bug.\n  * Internal error encountered."
 $ trace  :List of 4
  ..- attr(*, "class")= chr "rlang_trace"
 $ parent : NULL
 $ resp   :List of 10
  ..- attr(*, "class")= chr "response"
 - attr(*, "class")= chr [1:4] "gargle_error_request_failed" "rlang_error" "error" "condition"
Server error: (500) INTERNAL
  * Internal server error. Typically a server bug.
  * Internal error encountered.
List of 10
 $ url        : chr "https://sheets.googleapis.com/v4/spreadsheets/1CLwPasPsM24_l2beFfyO-wYKDAbNdaASP90bRGphuwE?fields=spreadsheetId"| __truncated__
 $ status_code: int 500
 $ headers    :List of 12
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 $ all_headers:List of 1
 $ cookies    :'data.frame':	0 obs. of  7 variables:
 $ content    : raw [1:109] 7b 0a 20 20 ...
 $ date       : POSIXct[1:1], format: "2020-04-02 21:23:57"
 $ times      : Named num [1:6] 0.00 6.00e-05 6.50e-05 1.80e-04 2.98e+01 ...
  ..- attr(*, "names")= chr [1:6] "redirect" "namelookup" "connect" "pretransfer" ...
 $ request    :List of 7
  ..- attr(*, "class")= chr "request"
 $ handle     :Class 'curl_handle' <externalptr> 
 - attr(*, "class")= chr "response"
```

**Comment by jennybc** [comment]
500s are on the server side (as they indicate). It has nothing to do with googlesheets4. How often are you reading this Sheet? Do you have any idea of the error rate? The fact that you're getting these failures "a couple of times a day" makes me think you are doing an awful lot of reads. In my experience, the error rates are very low.

If I'm right, then I'd look into ways to reduce that through some sort of caching. If you really must read the data over and over again, then I think you'll have to build in a retry strategy.

**Comment by behrman** [comment]
We were reading the spreadsheet with a script every hour. But given the intermittent read errors, we changed to a different approach that doesn't use Google sheets at all.

Many thanks for your explanation of how to catch and read errors. That made it clear that the problem was on the server side and not with our code.
