### ISSUE TITLE
saveRDS() for googlesheets4?

### ISSUE THREAD

**Issue by guhanrv** [tidyverse/googlesheets4#142]
Hi @jennybc,

I am sorry if this is a repetitive question (I accidentally originally commented this on the `googledrive` repository), but is there a way to generate a token RDS file like in the original googlesheets R package? Before, something like this used to work:
```
library(googlesheets)
token <- gs_auth(cache = FALSE)
gd_token()
saveRDS(token, file = "googlesheets_token.rds")
```
Is there an equivalent of this series of steps leading to a `saveRDS()` command for `googlesheets4`? Essentially, I want to retrieve and save a token to file. We are interested in this for repetitive non-interactive use.

**Comment by jennybc** [comment]
googlesheets4, googledrive, gmailr, and bigrquery now all use the same auth framework, which comes from a package called gargle.

Here are all the options for doing non-interactive auth:

https://gargle.r-lib.org/articles/non-interactive-auth.html

Without knowing any details of your situation, I can offer general advice for the Sheets API:

  * Use a service account token, if you can.
  * If there's some reason that can't happen or is really awkward, fall back to a regular user OAuth token, maybe using a Project-level OAuth token cache.
