### ISSUE TITLE
Can't Install Development Version

### ISSUE THREAD

**Issue by realauggieheschmeyer** [tidyverse/googlesheets4#144]
As per the **Installation** section on the README, I tried installing the development version of `googlesheets4`, but I keep getting version 0.1.1.9000. I've tried installing with both `devtools` and `remotes`, but neither seems to give me the up-to-date version of the package.

Is there something I am missing?

Please and thank you.

``` r
devtools::install_github("tidyverse/googlesheets4")
#> Downloading GitHub repo tidyverse/googlesheets4@master
#> 
#>      checking for file ‘/private/var/folders/jm/3kpdk9cn29x_x8ht1tkcy_9c0000gn/T/RtmpuHQc6Y/remotescee1d21ee52/tidyverse-googlesheets4-b5e46ee/DESCRIPTION’ ...  ✓  checking for file ‘/private/var/folders/jm/3kpdk9cn29x_x8ht1tkcy_9c0000gn/T/RtmpuHQc6Y/remotescee1d21ee52/tidyverse-googlesheets4-b5e46ee/DESCRIPTION’
#>   ─  preparing ‘googlesheets4’: (423ms)
#>      checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  installing the package to process help pages
#>   ─  checking for LF line-endings in source and make files and shell scripts (3.5s)
#>   ─  checking for empty or unneeded directories
#>   ─  looking to see if a ‘data/datalist’ file should be added
#>   ─  building ‘googlesheets4_0.1.1.9000.tar.gz’
#>      
#> 

library(googlesheets4)

packageVersion("googlesheets4")
#> [1] '0.1.1.9000'
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
0.1.1.9000 **is** the current development version of googlesheets4:

https://github.com/tidyverse/googlesheets4/blob/master/DESCRIPTION

It briefly was 0.2.0.9000, related to me doing a quick patch release (v0.1.1) for CRAN and doing an over aggressive version bump on the "real" dev version. I sorted that out here:

https://github.com/tidyverse/googlesheets4/commit/941de0fc041ea6e922a79a812ab667d0e63df606

**Comment by realauggieheschmeyer** [comment]
@jennybc given this, is there any particular reason why I wouldn't be able to access the writing functions with this version? I saw that there may be an issue with Macs, but it seemed like your advice was to install directly from GitHub.

**Comment by jennybc** [comment]
No I don't see how you could truly install AND load the current version from GitHub and not have access to the writing functions.

Are you definitely doing the basics like restarting R? Do you have any potentially funny business in a startup file? Any possibility of weird, multiple libraries and associated confusion? All of those seem more likely explanations for the mystery.

Also, when I do `install_github("tidyverse/googlesheets4")`, I see the output your show AND much more -- the actual installation:

```
Installing package into '/Users/jenny/Library/R/3.6/library'
(as 'lib' is unspecified)
* installing *source* package ‘googlesheets4’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (googlesheets4)
```

If you're not seeing that, I don't think you are managing to successfully install the package.
