### ISSUE TITLE
Store IDs of official examples in a Sheet; use static IDs as a fallback

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#145]
This could make the package more resilient to development mishaps that delete official examples. Unless of course this Sheet of IDs gets deleted! It should probably be owned by a dedicated service account.

**Comment by jennybc** [comment]
08549235ed08d158640ef607499db0893e7ef645 records something I did as intermediate progress. All important test and example sheets are now owned by a dedicated service account. It should be impossible for a development / testing / checking mishap to delete these now.

**Comment by heathyates** [comment]
I've been lurking. Still reading the issues and documentation. Still wrapping my head around this package. I am thinking the dedicated service account can be used to access all the test/example sheets and store the ids of official examples in a sheet as the next step?

**Comment by jennybc** [comment]
Done in cc1e50deab8b20598c0f147fc6afe9b401607efd
