### ISSUE TITLE
Error creating new sheets

### ISSUE THREAD

**Issue by ceprdata** [tidyverse/googlesheets4#151]
I'm getting `Error: 'field_mask' is not an exported object from 'namespace:gargle'` whenever I call `sheet_write()` or `gs4_create()`. I have no problems reading existing sheets.

**Comment by jennybc** [comment]
`field_mask()` is only present in the dev version of gargle.

You'll need to either update gargle (re-install from GitHub) or wait for it to go to CRAN. I literally hope to submit it in the next day.

**Comment by bayres1** [comment]
Reinstalling gargle from github did the trick for me. Remove the current gargle package from your R package directory before installing the github package.

**Comment by jennybc** [comment]
> Remove the current gargle package from your R package directory before installing the github package.

In general that is not necessary. But it never hurts and, it's true, that on Windows and with packages with compiled code (not true of gargle) this sometimes becomes necessary.

**Comment by ceprdata** [comment]
This worked for me. Thanks!
