### ISSUE TITLE
gs4_deauth() error

### ISSUE THREAD

**Issue by jpawlata** [tidyverse/googlesheets4#152]
I'm getting an error:
`Error in gs4_deauth() : could not find function "gs4_deauth"
`
while trying to work with googlesheets4 in de-authorized state.  

gs4 package has been installed using:
`> devtools::install_github("tidyverse/googlesheets4")
`
with the output:
   
```
Installing package into ‘/home/justyna/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘googlesheets4’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (googlesheets4)
```

my reprex:

```r
library(tidyverse)
library(googlesheets4)

gs4_deauth()

url <- "some_url"
data <- read_sheet(url)
```
Googlesheet I work with is public.

What is causing gs4_deauth error? What can I do to avoid it and work in de-authorized state?

**Comment by jennybc** [comment]
Did you restart R after installing from GitHub?

**Comment by jennybc** [comment]
Please put `packageVersion("googlesheets4")` in your reprex. `devtools::session_info("googlesheets4")` will also reveal whether the currently loaded googlesheets4 is from CRAN, GitHub or local and, if GitHub, what the SHA is.

---

If you use the reprex package I can see your actual output (e.g. package version and the GitHub SHA you have installed from).

https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html

**Comment by jpawlata** [comment]
Thank you, it's working. 

Steps I've done:
1. removed googlesheets4 package
2. restarted R session
3. installed googlesheets4 from GitHub 
4. restarted R session once again

Not sure what was causing the problem, my first installation log didn't show any error. What's interesting, read_sheet() function was working and asking for Google authentication. Anyway, following the four steps above resolved the issue. Thank you!
