### ISSUE TITLE
Problem using Knitr in R Markdown

### ISSUE THREAD

**Issue by AvinaHunjan** [tidyverse/googlesheets4#153]
Hi there, I can't seem to knitr my R markdown anymore after loading my google sheets into R using googlesheets4. Has anyone else had this problem and how do I fix it?

**Comment by jennybc** [comment]
Brief intro / overview of googlesheets4 auth:

https://googlesheets4.tidyverse.org/articles/articles/auth.html

"I just want my `.Rmd` to render."

https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my--rmd-to-render

Key highlight from that:

> TL;DR is that you need to successfully authenticate once in an interactive session and then, in your code, give gargle permission to use a token it finds in the cache.
