### ISSUE TITLE
Temporary problem writing to google sheets

### ISSUE THREAD

**Issue by nicholailidow** [tidyverse/googlesheets4#155]
Hi @jennybc. Thanks for your response!

Just to recap, I've been running a script via a cron job for months with no problem. But after updating to R4.0 a few days ago I've run into a problem *the first time* I try to write to google sheets in the script. Re-running the write-sheets call works fine.

Here is the traceback that I get after the first error. Re-running the same command again succeeds.

`> write_sheet(d1, ss="XXXXXX", sheet="Sheet1") <br/>

Writing to "Payment Schedule MIRROR"<br/>

Writing to sheet "Sheet1"<br/>

Error: Expected content type 'application/json' not 'text/html'. 

<!DOCTYPE html> 

<html lang=en> 

  <meta charset=utf-8> 

  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"> 

  <title>Error 408 (Request Timeout)!!1</title> 
  <style>... <br/>

> traceback() <br/>

14: stop(fallback) <br/>

13: signal_abort(cnd) <br/>

12: abort(glue_collapse(message, sep = "\n"), .subclass = "gargle_error_request_failed", 
        resp = redact_response(resp), ) <br/>

11: stop_request_failed(message, resp) <br/>

10: check_for_json(resp) <br/>

9: response_as_json(resp) <br/>

8: error_message(resp) <br/>

7: glue_collapse(message, sep = "\n") <br/>

6: is_null(msg) <br/>

5: validate_signal_message(message, class) <br/>

4: abort(glue_collapse(message, sep = "\n"), .subclass = "gargle_error_request_failed", 
       resp = redact_response(resp), ) <br/>

3: stop_request_failed(error_message(resp), resp) <br/>

2: gargle::response_process(resp_raw) <br/>

1: write_sheet(d1, ss = "XXXXXX", 
       sheet = "Sheet1") <br/>

> write_sheet(d1, ss="XXXXXX", sheet="Sheet1") <br/>

Writing to "Payment Schedule MIRROR"<br/>

Writing to sheet "Sheet1"<br/>

> `<br/>

I really appreciate your help. <br/>

Nicholai

**Comment by jennybc** [comment]
What auth method are you using? As in, a user oauth token or a service account or ???

**Comment by jennybc** [comment]
I'm trying to determine if there's any chance this is happening as part of token refresh/acquisition, as opposed to the main request.

**Comment by nicholailidow** [comment]
@jennybc I'm using
gs4_auth(token=readRDS("libsolar_googlesheets_token.rds"))

No problems with any read_sheet() calls, and I can successful write_sheet() after the first attempt.

**Comment by jennybc** [comment]
And it literally happens **every** time on the first `write_sheet()`? Can I see the whole script?

Intermittent timeouts will always be a problem. In the medium term, I plan to do more "catch & retry" in some cases. But I really want to know if there is some systematic problem vs. a need for retries.

**Comment by nicholailidow** [comment]
@jennybc Now I see it does seem to be related to something that happens above... maybe maxing out the api quota with a bunch of read_sheet() calls.
I assembled a replication dataset for you that just uses a csv file as input (rather than a bunch of read_sheet() calls)... but running this replication script works fine. 
From my end, it's super easy to just divide up the script into two parts, so I'll do that.
Feel free to close the issue. Thank you for your help.

**Comment by jennybc** [comment]
In terms of general workarounds that you control, you can insert some sleep to slow things down.

Or, even better, you should probably get your own oauth client or user a service account. One way or another, you should make sure to use assets own by your own GCP project. Then you won't be sharing quota with everyone else who uses googlesheets4.

https://gargle.r-lib.org/articles/get-api-credentials.html

It is possible that you need to combine these 2 measures, if you are really making a lot of requests.

**Comment by nicholailidow** [comment]
Thank you for the advice. I appreciate your help.

**Comment by ZainWahab** [comment]
Hi Guys,
Whats the fix here? As I am still getting the same error

**Comment by jennybc** [comment]
Read the comment that starts "In terms of general workarounds that you control ...".

gargle will soon get some retry capability. But that can never totally solve this problem. If a user is making lots of requests in rapid succession and hitting quota problems, it's probably time to use your own credentials and/or deliberately slow things down.
