### ISSUE TITLE
Show a more useful error when providing the result of `read_sheet()` as an argument to `

### ISSUE THREAD

**Issue by daattali** [tidyverse/googlesheets4#161]
This could be attributed to my lack of reading documentation and/or my silliness. But the fact that I ran into this means that others probably do too.

I haven't used this package in a long time so I forgot how to use it. I forgot that I can write directly to a google sheet without having to first read it. So I was trying to first `ss <- read_sheet(...)` into memory, I assumed that this returned some decorated tibble that has additional information about it being a googlesheet, and then I'd be able to use `write_range(ss, ...)` to modify it. 

That did not go as planned. 

```
Error: Don't know how to coerce an object of class 'tbl_df/tbl/data.frame' into a 'sheets_id'
```

It's actually not a bad error, it's very correct, but it still left me confused and I had to read the docs a lot more to realize that I'm completely butchering the workflow 🙈 

I tried this because in a lot of other packages this sort of workflow is the standard (I'm not saying it should be changed - the current is great!). Assuming I'm not the only person who has tried to do this, perhaps it'd be worthwhile to add a check in the write functions and if a dataframe is provided as the sheet parameter then give a more informative error. 

Or maybe I just need to RTFM 🤓

**Comment by jennybc** [comment]
I've labelled the other issues as feature requests, but I'm going to close this one. I don't get the sense that this is a common misstep and I don't think it's feasible to provide a much better error message. I'd have to special case data frame and then I would have to speculate what the user had done, which may or may not be correct.

> I assumed that this returned some decorated tibble that has additional information about it being a googlesheet, and then I'd be able to use `write_range(ss, ...)` to modify it.

The function that plays the role you are thinking of is `gs4_get()` (or, if you're specifying the Sheet by name `googledrive::get()`). The output of that is suitable as `ss` for a write.
