### ISSUE TITLE
Error with authentication

### ISSUE THREAD

**Issue by Helena-D** [tidyverse/googlesheets4#165]
I'm getting this error message when trying to read in a googlesheet using the googlesheets4 package: 

Can't get Google credentials. Are you running googlesheets4 in a non-interactive session? Consider: * `gs4_deauth()` to prevent the attempt to get credentials. * Call `gs4_auth()` directly with all necessary specifics. See gargle's "Non-interactive auth" vignette for more details: https://gargle.r-lib.org/articles/non-interactive-auth.html

I've specified my default browser.

**Comment by jennybc** [comment]
With this amount of information, it's impossible to say what's going on.

Are you seeing this interactively in the Console? Or when rendering `.Rmd`? Are you using RStudio? Or RStudio server? What was the exact code executed? What steps do you mean by "I've specified my default browser"? Is this a completely fresh install of googlesheets4 & gargle? What are their versions?

Here is a general troubleshooting document that might help you gather more information:

https://gargle.r-lib.org/articles/troubleshooting.html

**Comment by hforsythe** [comment]
I’ve been puzzled by the same error message after upgrading from googlesheets4 version 0.1.1 tp 0.2.0 about a week ago on my Mac with the latest version on Catalina.  I have scripts that worked before.  I’d load googlesheets4 In an R script and do a read_sheets that would take me to safari to authorize.  Now I get the same error as Helena-D.  
I don’t have this problem on my Windows PC or in rstudio cloud.  I suspect it’s “something” on my Mac but have not been able to isolate it.  Any ideas to try?

**Comment by jennybc** [comment]
> Any ideas to try?

Basically everything I said in the comment just above. I feel like I have no information to go on troubleshooting-wise.

**Comment by syu2** [comment]
Hi, I also have an issue with authentication using googlesheets4. I wrote my R script in a text editor (VS code) and tried to run it from a terminal. I followed the installation instructions on https://github.com/tidyverse/googlesheets4. 

```
library(googlesheets4)
gs4_auth()
range_read([google sheet url here])
```
The full terminal output I get is:

```
Using an auto-discovered, cached token.
To suppress this message, modify your code or options to clearly consent to the use of a cached token.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html
The googlesheets4 package is using a cached token for [google_account_name]@gmail.com.
Auto-refreshing stale OAuth token.
Error: Client error: (403) PERMISSION_DENIED
  * Client does not have sufficient permission. This can happen because the OAuth token does not have the right scopes, the client doesn't have permission, or the API has not been enabled for the client project.
  * Request had insufficient authentication scopes.
Backtrace:
    █
 1. └─googlesheets4::range_read(...)
 2.   └─googlesheets4:::get_cells(...)
 3.     └─googlesheets4::gs4_get(ssid)
 4.       └─googlesheets4:::gs4_get_impl_(as_sheets_id(ss))
 5.         └─gargle::response_process(raw_resp)
 6.           └─gargle:::stop_request_failed(error_message(resp), resp)
Execution halted
``` 
When I use `gs4_deauth()` for a google sheet that is accessible for anyone with link, everything works fine. I also checked my Google Account, and sure enough I don't see Tidyverse API Packages under "Third-party apps with account access". Any pointers for where I should look into?

**Comment by caspercrause** [comment]
Hmm, I also don't have much to go on here. But before upgrading R to version 4.0.2 I was able to to authorize a third-party service account to authenticate on my behalf as long as I granted editor's access to this account on googlsheets.

since upgrading, I suspect `garle` is not playing along.
The error message: ```
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html
```

session info: 
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252    LC_MONETARY=English_South Africa.1252
[4] LC_NUMERIC=C                          LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets4_0.2.0.9000

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11   magrittr_1.5      tidyselect_1.1.0  rjson_0.2.20      R6_2.4.1          rlang_0.4.7       httr_1.4.1       
 [8] dplyr_1.0.0       tools_4.0.2       packrat_0.5.0     ellipsis_0.3.1    tibble_3.0.3      gargle_0.5.0.9000 lifecycle_0.2.0  
[15] crayon_1.3.4      purrr_0.3.4       vctrs_0.3.2       fs_1.4.2          RAdwords_0.1.18   bitops_1.0-6      curl_4.3         
[22] RCurl_1.98-1.2    glue_1.4.1        compiler_4.0.2    pillar_1.4.6      cellranger_1.1.0  generics_0.0.2    jsonlite_1.7.0   
[29] googledrive_1.0.1 pkgconfig_2.0.3  
```

**Comment by muschellij2** [comment]
@caspercrause Are you using an Rmd?  If so, it's likely trying to work in the notebook environment.

You can add this to have it work in the console:
```yaml
editor_options: 
  chunk_output_type: console
```

Also, 
```r
token = readRDS(token_file); 
googlesheets4::gs4_auth(token= token)
```
can be used for non-interactive sessions.

**Comment by jennybc** [comment]
Providing a token directly as shown just above is possible but I consider it a less good option than many others explained here:

https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by caspercrause** [comment]
@muschellij2 Thanks for the quick reply! No the apps were not built with and .Rmd file. 

I got it working without any hiccups this morning. My problem specifically had to do with me upgrading to R 4.0 (something I deliberately avoided doing for a while) I copied all of my packages from my previous version (3.6) to 4.0 and just manually updated all the packages I saw fit(without taking dependencies into consideration) - big mistake. So I just removed all those packages from my 4.0 package folder and started installing the packages I most frequently use ( a long and overdue clean-up if you ask me). That did the trick for me. 

ps. I also make use of a  .json file and not a token for non-interactive authentication. 

Thanks @jennybc !

**Comment by jennybc** [comment]
Closing, because it seems like these issues are resolved.

For anyone who comes back in the future, it is true that this sort of auth failure can happen in a notebook.

Specifically, initiating OAuth2 web flow didn't work if you were in a notebook AND you have "Chunk output inline", because we (mistakenly) thought we were not in an interactive session.

The workaround is to trigger auth in some other context, i.e. not from a notebook or with chunk output in console.

However the definitive solution was for us to change something in `rlang::is_interactive()` (https://github.com/r-lib/rlang/commit/4513283d8640275e53d232af02ef342abaf3870c), so this will eventually self resolve when rlang releases and that version becomes prevalent. This should make gargle auth play more nicely with notebooks + chunk output inline.

---

General advice about non-interactive auth is here:
https://gargle.r-lib.org/articles/non-interactive-auth.html
