### ISSUE TITLE
Error with out of band auth

### ISSUE THREAD

**Issue by pschloss** [tidyverse/googlesheets4#167]
I'm getting an error about `httpuv` not being installed when I enter "0" when prompted after running the following code...

```r
library(tidyverse)
library(googlesheets4)

sheet <- read_sheet('https://docs.google.com/spreadsheets/d/1_quMjJRBHDLQSmWQouzzyi1DOejAtCZnAeesdVyRWiQ/edit#gid=1467293328',
	range = 'A:J',
	col_types="Dncccccccc",
	na="NA")
```

Here are the dialog and error messages...

```
The googlesheets4 package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: pschloss@umich.edu

Selection: 0
httpuv not installed, defaulting to out-of-band authentication
Enter authorization code: LSOpenURLsWithRole() failed with error -600 for the URL https://accounts.google.com/o/oauth2/auth?client_id=REDACTED.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code.
```

I get the same thing running the code on the RStudio console or from R in a terminal. I know that running `gs4_deauth()` before this gets things to work nicely since it's a public workbook, but getting the error message seems wrong. If I'm teaching people to use gs4 should there be an extra installation step of installing `httpuv`? I'd like for them to be able to take the next step of working with workbooks that are not public with minimal friction. FWIW if I do install `httpuv` things work.

```r
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] googlesheets4_0.2.0 forcats_0.5.0       stringr_1.4.0      
 [4] dplyr_0.8.5         purrr_0.3.4         readr_1.3.1        
 [7] tidyr_1.0.2         tibble_3.0.1        ggplot2_3.3.0      
[10] tidyverse_1.3.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      cellranger_1.1.0  pillar_1.4.4      compiler_4.0.0   
 [5] dbplyr_1.4.3      tools_4.0.0       gargle_0.5.0.9000 googledrive_1.0.1
 [9] jsonlite_1.6.1    lubridate_1.7.8   lifecycle_0.2.0   nlme_3.1-147     
[13] gtable_0.3.0      lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.6      
[17] reprex_0.3.0      cli_2.0.2         rstudioapi_0.11   DBI_1.1.0        
[21] curl_4.3          haven_2.2.0       withr_2.2.0       xml2_1.3.2       
[25] httr_1.4.1        askpass_1.1       fs_1.4.1          generics_0.0.2   
[29] vctrs_0.3.0       hms_0.5.3         grid_4.0.0        tidyselect_1.0.0 
[33] glue_1.4.1        R6_2.4.1          fansi_0.4.1       readxl_1.3.1     
[37] modelr_0.1.7      magrittr_1.5      backports_1.1.6   scales_1.1.0     
[41] ellipsis_0.3.1    rvest_0.3.5       assertthat_0.2.1  colorspace_1.4-1 
[45] stringi_1.4.6     openssl_1.4.1     munsell_0.5.0     broom_0.5.6      
[49] crayon_1.3.4     
```

**Comment by jennybc** [comment]
I'll have to de-install httpuv to see if I can replicate the error you see above, but I'm working on something else right now.

But I will say that the OAuth flow in the browser is much, much nicer than oob auth.

So if the goal is for people to have a good googlesheets4 experience, I think having httpuv installed is the way to go. I think lots of people *do* have it installed, without conscious effort, because it is an (indirect) dependency of some heavy-hitter packages like shiny (Imports) and curl and httr (Suggests).

It's somewhat out of my hands as the dependency comes into googlesheets4 indirectly:

googlesheets4 --> gargle --> httr (which Suggests httpuv vs. Imports)

It would be weird for googlesheets4 to imitate a direct relationship or dependency on httpuv.

So I think I am OK with someone seeing this suggestion (which BTW is emitted by httr, not googlesheets4 or gargle):

```
httpuv not installed, defaulting to out-of-band authentication
```

The error you're seeing seems odd to me though, so I will look into that. You should be able to do oob auth.

**Comment by pschloss** [comment]
Thanks, Jenny. Perhaps this is more of a documentation problem then.

FWIW, I had never heard of `httpuv` before this came up and have never installed `shiny`, `curl`, or `httr`. I don't think my experience is that far outside the norm. I would have gotten the same error message running 

```
read_sheet("https://docs.google.com/spreadsheets/d/1U6Cf_qEOhiR9AZqTqS3mbMF3zt2db48ZP5v3rkrAEJY/edit#gid=780868077")
```

Perhaps telling people to install `httpuv` with the installation instructions. Also, from reading the https://googlesheets4.tidyverse.org description, I'm not sure what the difference is between OAuth flow and oob auth or how I do one rather than the other.

**Comment by jennybc** [comment]
I still don't see a clear solution to this feels like a net positive for the package. Neither googlesheets4 nor gargle has a direct relationship to httpuv.

If someone's preparing code for a broad audience to use and they're reading a public Sheet, I think the code should kick off with:

``` r
library(googlesheets4)

gs4_deauth()
```

If it's a private Sheet and the user will need to authenticate themselves with Google, I think the current experience is OK. I de-installed httpuv, removed all existing tokens, and succeeded, so the error above is not inevitable and I'm not sure what it is:

``` r
> library(googlesheets4)
> sheet <- read_sheet('https://docs.google.com/spreadsheets/d/1_quMjJRBHDLQSmWQouzzyi1DOejAtCZnAeesdVyRWiQ/edit#gid=1467293328',
+ 	range = 'A:J',
+ 	col_types="Dncccccccc",
+ 	na="NA")
httpuv not installed, defaulting to out-of-band authentication
Enter authorization code: 4/1AY...wxVk
✓ Reading from lamb_prices
✓ Range A:J
```

If you really want people to have the nicest auth experience (with googlesheets4 and, indeed, any package that eventually uses httr for OAuth), then I'd make sure the package installation instructions included something that caused httpuv to be installed:

``` r
install.packages("googlesheets4")
# AND
install.packages("httpuv")
# or perhaps
install.packages("httr", dependencies = TRUE)
```
