### ISSUE TITLE
Permission denied while trying to use service account token

### ISSUE THREAD

**Issue by tomcardoso** [tidyverse/googlesheets4#170]
Hi there! First off, thanks for making this great, well-documented package. I'm having what seems to be an authentication issue on a sheet I'd like to read. I've created a service account token in GCP and stored it as an environment variable, which I'm reading in this way:

```r
gs4_auth(
  scopes = 'https://www.googleapis.com/auth/spreadsheets',
  path = Sys.getenv('GOOGLE_DRIVE_KEY')
)
```

With `options(gargle_quiet = FALSE)`, here's what I see:

```
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
service account email: EMAIL_ADDRESS.iam.gserviceaccount.com
```

However, when I try to do `read_sheet("MY_SHEET_URL")`, I get this:
```
attempt from: googlesheets4
Error: Client error: (403) PERMISSION_DENIED
  * Client does not have sufficient permission. This can happen because the OAuth token does not have the right scopes, the client doesn't have permission, or the API has not been enabled for the client project.
  * The caller does not have permission
```

Am I missing something or doing something wrong? I'm hoping to run this script as a cron job every 5 minutes on Heroku, so I'm trying to sort out the non-interactive auth workflow where I don't need to renew keys constantly, hence my using service account creds. Any help would be much appreciated!

**Comment by jennybc** [comment]
Is there any chance you're using Docker on Windows?

**Comment by jennybc** [comment]
Who owns the Sheet? Is it the service account? If not, has the service account been granted access?

**Comment by tomcardoso** [comment]
@jennybc Ahhh, thank you so much, granting access was the issue. I thought that simply owning the sheet and the service account from the same Gmail account would do it — I missed that I needed to share the spreadsheet to my service account's email address. Good grief, every time I use GCP it's always a nightmare… thanks so much for your help.

**Comment by daattali** [comment]
That tip from @jennybc probably saved me hours. Or days. Or abandoning this project altogether!

Is the fact that a service account's awkward email needs to be an owner of a sheet in order to allow me to edit mentioned in the docs? I didn't see it so apologies if it is.

**Comment by jennybc** [comment]
I don't think the service account needs to *own* the Sheet but yeah it needs write permission to write. I don't think I've documented that specifically, but it strikes me as ... something you'd expect? Any google account would need relevant permissions on a Sheet to read or write it, as the case may be. And a service account is actually a separate special Google account owned by a GCP project. It's not just an extension of a normal user.

**Comment by daattali** [comment]
That's true, it does fully make sense when you think about what you're doing.

But if you've never used service accounts before and are just following the step by step guide in the package documentation, those steps look intimidating and it's hard to understand what's happening. The other steps are so detailed so you might expect things to just work when you finish the instructions. I've had people email me saying that they've tried but failed to use Google sheets in shiny apps, and I never looked into it before but maybe this missing step was the reason at least some of them were stuck. Anyway, I don't need this documentation but just wanted to point out to might be helpful :)

**Comment by kwindii** [comment]
@jennybc I wish I saw your comment hours ago before all this frustration! Thank you a lot for sharing this non-obvious obvious detail!

**Comment by jennybc** [comment]
Obviously it's not obvious! 😬
There will be a big simultaneous release of gargle, googledrive, and googlesheets4 soon-ish and I'll make sure this gets into the docs.

**Comment by sophicist** [comment]
> the third option must be checked to avoid such issue you met, here is an example: ![WeChat Photo Editor_20221204151629](https://user-images.githubusercontent.com/105121687/205513451-a8554e84-17ba-4f4f-be1e-5c2894773432.jpg)

This worked for me

**Comment by jennybc** [comment]
These last two comments (about checking a box re: scopes) are marked and hidden as off-topic here because they pertain to an entirely different auth flow. If you are using a service account, you will never see such a dialog. That dialog implies you are auth'ing as a regular user.
