### ISSUE TITLE
Automated (non-interactive) authentication - something that would work on shinyapps.io

### ISSUE THREAD

**Issue by RussBowdrey** [tidyverse/googlesheets4#173]
I can't begin to tell you how grateful I am for this package. Thank you. Apologies if I've not read the docs thoroughly enough and this isn't an issue/feature request, but is in realty a "question".

I'm trying to create a shiny app that pulls a sheet from a googlesheets (using googlesheets4 and presents it (then does some stuff with it, etc and posts it back)

When I run the app from RStudio I sometimes get asked to choose a pre-authorised account. (having stored the pre-auth'd token in the www folder).

Now, when I deploy this app, initially to shinyapps.io this sort of interactivity, I presume, isn't going to be possible - and really I'd prefer it to be hidden. So is it possible (or could it please become possible?) to somehow work round this?

Having tried to make sense of the lower level functions (and failing) I wondered if a possible feature could be somehow streamline this non-interactive auth?

**Comment by Brunox13** [comment]
You should be able to do exactly that fairly easily by following this `gargle` package article: [Non-interactive auth](https://gargle.r-lib.org/articles/non-interactive-auth.html)

Note especially the following passage:

> Let’s identify a specific type of project: it is developed in one place, with interactivity – such as your local computer – and then deployed elsewhere, where it must run without further interaction – such as on RStudio Connect or **shinyapps.io**. In this context, it may make sense to depart from gargle’s default behaviour, which is to store tokens outside the project, and to embed them in the project instead. An example at the end of this vignette demonstrates the use of a [project-level OAuth cache](https://gargle.r-lib.org/articles/non-interactive-auth.html#project-level-oauth-cache).

Only instead of the `drive_*` functions, you'll be using the `gs4_*` ones - e.g., instead of `drive_auth()` function, you'll use `gs4_auth()`.
