### ISSUE TITLE
gs4_browse not opening in a new tab when application is deployed on shiny server

### ISSUE THREAD

**Issue by milamyslov** [tidyverse/googlesheets4#176]
I have been using gs4 for an application I am developing and largely all is working really well!

The issue I am experiencing is that I would like to automatically open the new sheet that I create on the app. gs4_browse works fine and does what I need it to do when I test on my local machine, but when I deploy the app on the server the sheet doesn't open automatically.

snippet of my code:

new_sheet <- gs4_create(sheet_name, sheets = list(Details = meta_data , Setup = setup_information))
gs4_browse(new_sheet)

Apologies if I have missed something somewhere - any help would be greatly appreciated :) 

Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.
Special tricks for this package are in [How to create a googlesheets4 reprex](https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html).

Brief description of the problem

```r
# insert reprex here
```

**Comment by jennybc** [comment]
I don't know how to change this behaviour off the top of my head, so if you feel like doing any research on the matter, that would probably accelerate things. It sounds like a Shiny matter.

**Comment by milamyslov** [comment]
Hi Jenny - that's fair enough!
 
For the time being I have done a work around which generates a href link that the user can click to open the sheet, but I will try to look into making this a bit more fluid in future. Will let you know what I find out!

**Comment by jennybc** [comment]
I'd be happy to do better if anyone has concrete suggestions. When/if that day comes, we can open a new issue.
