### ISSUE TITLE
Split rows creation to bypass the 40,000 new rows at a time limit?

### ISSUE THREAD

**Issue by OmarGonD** [tidyverse/googlesheets4#177]
I've tried to upload a df with 229507  rows and 6 cols, assuming no problem since the limit of cells is 5 million.

However, I got the error: 

![image](https://user-images.githubusercontent.com/7775734/89125376-956e1a00-d4a3-11ea-9fa8-c0bab4a26762.png)

**Error message:** This action will increment the cell number of the book above the 5 million limit. 

Which is not accurate since we're uploading 1 million data cells (229,507   x 6). 

The error seems to come from another limitation of the API: **40,000 new rows at a time, according to [this]**(https://gsuitetips.com/tips/sheets/google-spreadsheet-limitations/#:~:text=Google%20Spreadsheets%20are%20extremely%20powerful,of%20columns%20of%2018%2C278%20columns):

![image](https://user-images.githubusercontent.com/7775734/89125408-ec73ef00-d4a3-11ea-9aec-305897cf8f17.png)

**Solution:**

Manually splitting the df and uploading the data makes the trick. 

I've taken only the first 1000 rows of the data frame and uploaded without issues.

Is there a function to split a large data frame and upload each chunk?  Would be nice to implement one if possible.

Thank you.

**Comment by jennybc** [comment]
There's nothing pre-built for this, no. It's my first report of it.

If you want to implement your own solution for now, `googlesheets4::sheet_append()` should be a key player, in order to keep delegating the exact placement of the new data to Sheets.

**Comment by OmarGonD** [comment]
I think I'll be using this for now, pasting it here, in case it is of any help. 

```
chunk_limit <- 40000
n <- nrow(data_frame)
r  <- rep(1:ceiling(n/chunk_limit),each=chunk_limit)[1:n]
d <- split(data_frame,r)
d

lapply(d, sheet_append)
```

**Comment by douglascm** [comment]
Im not even able to update 2k rows, and I'm getting error 408 timeout

**Comment by jennybc** [comment]
I hope that this has somehow self-resolved or self-improved since 2020. It remains unclear what if anything googlesheets4 could really do about it, since it's basically a limitation from the API.
