### ISSUE TITLE
Error while trying to read sheet with "read_sheet"

### ISSUE THREAD

**Issue by marcusbrito** [tidyverse/googlesheets4#178]
Hey, I'm simply trying to read a sheet from my google drive.

I'm doing:

```
install.packages("googlesheets4")

library(googlesheets4)

read_sheet(sheet-url)
```

Then a tab in google chrome opens, and I authorize access.

Then I get the following error:

Error: Client error: (400) FAILED_PRECONDITION
  * Request can not be executed in the current system state, such as deleting a non-empty directory.
  * This operation is not supported for this document

Can someone please help me with this? I'm just trying to read a spreadsheet, I didn't think it was going to be that complicated.

 I have reinstalled the package several times, I tried to follow all possible tutorials, but nothing solved the problem.

**Comment by jennybc** [comment]
No one has ever reported this error before. But I would take it at face value, especially this part:

> This operation is not supported for this document

I googled "Client error: (400) FAILED_PRECONDITION Google Sheets". There's a lot of possible leads. Here's one example:

https://forum.getodk.org/t/error-400-bad-request-failed-precondition-on-collect-to-google-sheets/19801/4

The TL;DR there is that this person seems to be trying to read an Excel workbook (that is stored on Drive) as a Google Sheet. Is that perhaps your problem?

Have you tried to read any other Sheet, such as one of the example Sheets to try to figure out the problem is unique to this particular file?

**Comment by muschellij2** [comment]
I have found that if you're automatically uploading stuff to drive (not via
web app - I think there is a "convert" button), I use:

googledrive::drive_upload(
    media = "/path/to/excel.xlsx",
    type = googledrive::drive_mime_type("spreadsheet"))

(to be clear I really have done this with PPTX to presentation, but I think
same principle applies)

Best,
John

**Comment by muschellij2** [comment]
I have found that if you're automatically uploading stuff to drive (not via web app - I think there is a "Open in Sheets" button), I use:
```r
googledrive::drive_upload(
    media = "/path/to/excel.xlsx",
    type = googledrive::drive_mime_type("spreadsheet"))
```
(to be clear I really have done this with PPTX to presentation, but I think
same principle applies)
Edit: I just checked, it does work.  Not a solution to the problem above, but could be "fixed" using `drive_download` then `drive_upload`.

**Comment by jennybc** [comment]
FWIW, yes the above snippet is definitely how to upload `.xlsx` into a proper Google Sheet and that is definitely different than uploading an `.xlsx` onto Drive (w/ no conversion). Still not clear if this is the problem in this case, though, but I suspect it's something along these lines.

**Comment by marcusbrito** [comment]
@jennybc @muschellij2 

It worked! Thank you very much!

The original file was in deed an .xlsx. I just created a empty new file directly on google sheets, and copied the content of the original file to it.

I can read it correctly now.

**Comment by amstilp** [comment]
I ran into the same error five years later 🙃 with an xlsx file in Google Drive. Adding my solution in case it helps anyone else. I didn't want to create a new copy, so instead I used the following code to download it as into a temporary file and then read it in to R from the temp file:

```
library(googledrive)
library(readxl)

dl <- drive_download(
    as_id(url),
    path = tempfile(),
    overwrite = TRUE
)
xl = read_excel(dl$local_path)
```
