### ISSUE TITLE
Import non-standard columns as character (not lists)

### ISSUE THREAD

**Issue by lucasmation** [tidyverse/googlesheets4#18]
When I import data from  a spreadsheet some "non-standard" columns such as:

-  dates in DD/MM/YYYY format or 
- Columns mixing numbers in most cells but some numbers with comma separator ("2,5") and some NA and NULL values

`read_sheet` defaults to reading them as lists, which generates a complicated object (a tibble with embedded lists) to work with. It would be nice to just cast these columns as characters, as most other reading functions in R (and tidyverse) do. 

Of course, I can control this by declaring col_types, but that is a lot of work for something that is usually automatic when importing.

Here is an example:

```
> e <- read_sheet('bla_bla_bla',sheet='eletricidade', col_types = ) #data is confidential, can not provide reproducible example

> e %>% select(UF,`DATA DA PROCURA`,`kWh - Out/17`) %>% data.table %>% str
Classes ‘data.table’ and 'data.frame':	998 obs. of  3 variables:
 $ UF             : chr  "SP" "SP" "SP" "SP" ...
 $ DATA DA PROCURA:List of 998
  ..$ : chr "22/10/2018"
  ..$ : chr "22/10/2018"
  ..$ : chr "22/10/2018"
  ..$ : chr "17/10/2018"
  ..$ : chr "18/10/2018"
  ..$ : chr "18/10/2018"
  .. [list output truncated]
 $ kWh - Out/17   :List of 998
  ..$ : chr "3305,8"
  ..$ : chr "NA"
  ..$ : chr "2206,3"
  ..$ : num 1073
  ..$ : chr "NA"
  ..$ : NULL
  ..$ : NULL
  ..$ : num 1774
  ..$ : num 8378
  ..$ : chr "NA"
  ..$ : chr "NA"
  .. [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr> 

```

**Comment by jennybc** [comment]
I know that the `col_types` interface has to get more sophisticated. Among other things, you need to be able to specify a default col type, as one can do in readr. And someone with your preferences could use that to coerce things to character, by default, instead of using a list-column. So I consider this use case covered by #51.
