### ISSUE TITLE
How to address Google's security concern with tidyverse

### ISSUE THREAD

**Issue by sanjmeh** [tidyverse/googlesheets4#180]
This is really not a bug or even a feature request. We can call it a security 'guideline request'. 
Since all of googlesheets4 and also googledrive package use google APIs, we have all given full access to the tidyverse on our google documents. There are sensitive documents stored in the google drive that we do not want the app to have access to but it seems there is no way to restrict access to certain folders only.

Google has become very proactive in reminding us and flagging clearly when a certain app has 'unlimited' access.
![Screenshot 2020-08-12 at 09 42 16](https://user-images.githubusercontent.com/3091624/89975133-9876c080-dc82-11ea-9191-0cc219b4c6c9.png)

My question is, are there any best practices to limit the security risk while using tidyverse packages seamlessly with google?

**Comment by jennybc** [comment]
First: I don't actually recognize the "tidyverse-googlesheets" app. The main tidyverse/gargle app IS verified and shows up as "Tidyverse API Packages". So I would seriously consider removing access for "tidyverse-googlesheets" and seeing what breaks / requests re-authorization. I work with googledrive and googlesheets4 all the time and I see no such third party app authorized for my account.

---

You can always create your own OAuth app and/or use service accounts and never authorize the tidyverse app:

https://gargle.r-lib.org/articles/get-api-credentials.html

To be clear, the tidyverse has NO ACCESS to your documents. It is regrettable that the various wording suggests that we do. But, when you use tidyverse packages, with the built-in OAuth app, you have a obtained a token that uses our client ID and secret. But what you do with that token is completely up to you. Perhaps reading the Privacy Policy can help bring more clarity:

https://www.tidyverse.org/google_privacy_policy/

**Comment by sanjmeh** [comment]
Aah! 
I have immediately disabled access. Many thanks @jennybc to notice that risk and flag it off.
How on earth did `tidyverse-googlesheets` get an approval from my google account unless it came from, well, tidyverse world - where else could it be from? Could it be the older version of googlesheets? I have used gmailR, googlemaps, ggmap and other google apis - all through R. Not sure which one took my approval. 
In any case, I will read those articles to strengthen my understanding.

**Comment by jennybc** [comment]
> How on earth did tidyverse-googlesheets get an approval from my google account unless it came from, well, tidyverse world - where else could it be from? Could it be the older version of googlesheets?

I'm not sure. I've thought about it too. I sure hope it was from a previous oauth app, although I don't have a specific memory of that ever being an app name. But it's not easy (maybe impossible) for me to reconstruct that. It's good that you revoked access and I believe you should not get bugged about the current, official app in the same manner, because it is verified. And, as I said above, if you have remaining concerns, you can get your own OAuth app and configure all of these package to use that. It is not that difficult to do.

**Comment by jennybc** [comment]
One last intermediate measure you could take: manage scopes very actively.

The default scope for googledrive is "https://www.googleapis.com/auth/drive" which is very powerful:

> See, edit, create, and delete all of your Google Drive files

But googledrive (and googlesheets4) allows you to obtain tokens with more limited scope, described here:

https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html#scope-savvy-1

If you can handle the limitation, you could, for example, always work with googledrive using a token with scope "https://www.googleapis.com/auth/drive.file" which does:

> View and manage Google Drive files and folders that you have opened or created with this app

That would work if you only want to work with files from googledrive *that you also created with googledrive*. That's a pretty big limitation.

And for both googledrive and googlesheets4, using "read only" scopes should be on your radar.
