### ISSUE TITLE
sheet_append () Error in : `data` must be a data frame: * `data` has class 'matrix/array''

### ISSUE THREAD

**Issue by TMax66** [tidyverse/googlesheets4#181]
Hi, 
I'm develop a shiny app that use googlesheet4 to read and modify sheet, according to a procedure to persistent storage data by Dean Attali at this link https://deanattali.com/blog/shiny-persistent-data-storage/. In this procedure it is used the googlesheet library and not the new googlesheet4. 
In the app there is a function to gather many user input control saved in a  object that is a  matrix  with dimension 1 row and 22 columns. Then another function call the sheet from googledrive and add  a new row using the data in the matrix. I have a couple of old app working perfectly that using googlesheet package. In this new app I'm using the new googlesheet4 and to add the new row I'm using

```r
sheet_append(mysheet, data)

```
where mysheet come from ``` read_sheet()``` and data came from this:
```r
    data <- sapply(campi, function(x) input[[x]])
    data <- t(data) 
    data
```

after using sheet_append() get this error : ```Error in : `data` must be a data frame: * `data` has class 'matrix/array'' ```

I tried to convert data in a data.frame usign data.frame(data)  but I get this error:

```
Warning: Error in : Don't know how to coerce an object of class 'tbl_df/tbl/data.frame' into a 'sheets_id'
 
```
any suggestion to fix it?

Thank you very much
Massimo

**Comment by jennybc** [comment]
Converting `data` to a data.frame is the correct thing to do.

There's no way simply doing that results in this error:

```
Warning: Error in : Don't know how to coerce an object of class 'tbl_df/tbl/data.frame' into a 'sheets_id'
```

That makes it sound like you've successfully created a data frame, but then are providing it to an argument that's meant to hold a Sheet ID.

Without actual working (or erroring) code that I can run and that shows a complete story, it's hard to be of more help.

**Comment by TMax66** [comment]
Thanks Jenny, 
in the old app, I used this line to save a new record on my sheet:
```r
sheet <- gs_title("mysheet")
    # Add the data as a new row
    gs_add_row(sheet, input = data)
```
I don't know if this can be helpful to understand what I would do.... 

How can I send you all code of my shiny app considering that data are in  my googledrive ...Do have I to give you the .secrets to acces my drive?

thank you Massimo

**Comment by jennybc** [comment]
> How can I send you all code of my shiny app

I don't think that is necessary. I think you need to run a small example, outside of shiny, with `sheet_append()` and get the syntax right. Then transfer that knowledge into your app.

The `sheet_append()` docs show lots of usage:

https://googlesheets4.tidyverse.org/reference/sheet_append.html

**Comment by TMax66** [comment]
Fixed, 
my ss argument of ``` sheet_append() ``` was a data.frame , so  after using ```as_sheets_id (mysheet)``` all working. 
Thanks a lot 
Massimo

**Comment by MateusMaiaDS** [comment]
I obtaining the same error @TMax66, even if I using a gs4_death()

``
Warning: Error in : Client error: (400) INVALID_ARGUMENT
  * Client specified an invalid argument. Check error message and error details for more information.
  * Invalid JSON payload received. Unknown name "sede" at 'requests.append_cells.rows': Cannot find field.
``

**Comment by jennybc** [comment]
@MateusMaiaDS as I explained in #182, you can't modify a Sheet after executing `gs4_deauth()`. This thread is about something else. You are not seeing the same error as @TMax66 (e.g. 400 INVALID_ARGUMENT is different from 403 PERMISSION_DENIED).

**Comment by TMax66** [comment]
Hi jenny, about the error have you some idea to fixed?
Thanks
Massimo

**Comment by TMax66** [comment]
Dear Jenny, I think this topic can be closed. While I was trying to build a simple example the error disappeared, I then rewrote the app starting from the new small example and everything works. I did not understand what went wrong in the previous version of the app but I think it is a problem related to other functions not in the googlesheet4 package. Thanks so much
Massimo

**Comment by jennybc** [comment]
Thanks for following up. Since you opened the issue, you can close it. But I will do so in this case.
