### ISSUE TITLE
Client error: (401) UNAUTHENTICATED - Using GoogleSheets4 in Shiny

### ISSUE THREAD

**Issue by MateusMaiaDS** [tidyverse/googlesheets4#182]
Hello all,

I having some issues to use the googlesheets4 in a deployed shiny application. Despite I use the  `r gs4_deauth()`, I obtaining a denied access to modify the google sheet, and obtain a error which close my application. Here the following

```r
Warning: Error in : Client error: (401) UNAUTHENTICATED
  * Request not authenticated due to missing, invalid, or expired OAuth token.
  * Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

**Comment by jennybc** [comment]
You will never be able to modify a Google Sheet if you are interacting with the API **without** sending a token, which is the mode `gs4_deauth()` puts you into.
