### ISSUE TITLE
"Call `gs4_auth()` directly with all necessary specifics"

### ISSUE THREAD

**Issue by MateusMaiaDS** [tidyverse/googlesheets4#183]
I writting a ShinyApp and require that the user can write a GoogleSheet. Its asked to call with all necessary specifics, which would be that?

**Comment by jennybc** [comment]
Who owns the Sheet? You / the app or are you hoping for the user to work on a Sheet that they own? Is it a specific, fixed Sheet or does it vary, because it's a "bring your own Sheet" situation?

If it's the latter, then making this fluid is being tracked already as https://github.com/r-lib/gargle/issues/14. I am working with the Shiny team on a joint resolution of that.

If it's the former, that's solvable with existing technology.

**Comment by MateusMaiaDS** [comment]
Hi 
It's mine sheet, is an editable sheet you can check it through the link https://docs.google.com/spreadsheets/d/1nW0jD5zzhKc6QKXsi3Lt-yzABMWzavqiuvkkCj3vWH0/edit#gid=0. When I use the `r gs4_auth() `  in my local machine it works. However if I use in the deplyoed version using shiny.io result in a error that ask for authentication, and ask to  **"Call `gs4_auth()` directly with all necessary specifics"**

**Comment by jennybc** [comment]
If it is a single fixed Sheet, then you could give a service account write access, place the service account token file somewhere your app can see it, and call `gs_auth()` with that from your app's code. You do need to keep that service account token secure, i.e. if you post the app source publicly, don't include the token.

There currently is no nice workflow for allowing the user of your app to auth as themselves.

**Comment by jennybc** [comment]
There has been success in https://github.com/tidyverse/googlesheets4/issues/184#issuecomment-685807305 and it did boil down to doing exactly what is documented in gargle's non-interactive auth vignette.

Note: that only applies to a Sheet that the app has write access to. The use case that remains effectively unsolved (solutions exist but they are not user-friendly) is where the app acts on a Sheet that is potentially private to the app user.

**Comment by MateusMaiaDS** [comment]
@jennybc Thank you so much! Now worked in here. Just a advice for everyone else. Do you need to create a token with `gs4_token()` save it as a .RDS file, and then read and use the #184 (comment) that Jenny mentioned.

I will close this topic by now.
