### ISSUE TITLE
Typo on README.md (function has been renamed?)

### ISSUE THREAD

**Issue by rpcach** [tidyverse/googlesheets4#186]
https://github.com/tidyverse/googlesheets4#write

gs4_create( ) should be replaced with sheets_create( )
sheet_write( ) should be replaced with sheets_write( )

**Comment by jennybc** [comment]
No the README really does reflect current function names:

https://googlesheets4.tidyverse.org/news/index.html#function-naming-scheme

Maybe you have an older version of the package.
