### ISSUE TITLE
Feature request: reading data from Google BigQuery-connected sheets.

### ISSUE THREAD

**Issue by felixetorres** [tidyverse/googlesheets4#192]
Currently, you can't read data from Google Sheets if the data is sourced from a data connector like Google BigQuery. For example, the following code gives an error:

```r
library(tidyverse)
library(googlesheets4) 

datawb <- "https://docs.google.com/spreadsheets/d/1yOG0uSBHoOFqi0JN_GP6-H6mQ2OGg2H_JzQlHaMBR-E/edit#gid=237305484" # where the URL links to a Google Sheet containing data sourced from BigQuery
data <- read_sheet(ss = dwb, sheet = 2)

# Error:
# Error: Properties not recognized for the 'SheetProperties' schema:
#  * dataSourceSheetProperties
```

Other reading works just fine. I wonder if this addition has been considered. I know this isn't a completely reproducible example, but that's a bit hard to do since you'd need a BQ license (I think?) to access that service.

**Comment by jennybc** [comment]
Just from reading your post, I think this just means I need to update the internal data object that describes the Sheets API. Perhaps this is a new field that has appeared.
