### ISSUE TITLE
gs4_formula and iterative calculations?

### ISSUE THREAD

**Issue by nilescbn** [tidyverse/googlesheets4#195]
I don't know if this is a bug or not, but any insight into what's going on would be very much appreciated. 

And first, I wanted to express appreciation for this package. It's fantastic and makes life easier. Thank you.

I will also beg for forgiveness in not having a reprex yet. I'm puzzling through how to come up with one. The issue is I have series of dependent equations/circular references that I'm not sure how to mimic. I thought I'd get the post started with the info I have now and see if I could come up with a reprex next. 

I've [posted a bit more detail in the RStudio Community forum](https://community.rstudio.com/t/googlesheets4-and-formulas/85676). In writing that up, I began to think this was the more appropriate place.

The quick way to explain the issue is that I can get Sheets' iterative calculation to work if I manually remove the leading ' marks in the formulas with Find and replace. If use gs4_formula() to convert the formulas first, I get #ERRORs where there are circular references. They're error types 8, which Sheets' documentation stands for "for all other errors".

Here's a screenshot of the spreadsheet after I've replaced the leading commas with Find and replace:

![image](https://user-images.githubusercontent.com/9826806/97031249-d27f0100-1514-11eb-86ab-12f6e22083bb.png)

Here's one where I converted with gs4_formula():

![image](https://user-images.githubusercontent.com/9826806/97031307-ecb8df00-1514-11eb-8a09-ca39cd3996d6.png)

The "check_sum" column sums what I've labeled columns A through E. The iterative calculation step is needed to get all rows to sum to 1. The "sheet_row" column is just something I added to make sure the formulas I was creating in R were referencing the correct spreadsheet row. 

I created both with this code:

```
gs4_create(name = "do iterative calculation",
           sheets = to_gs_setup,
           iterativeCalculationSettings = list("maxIterations" = 10000,
                                               "convergenceThreshold" = 0.00001))
```

It's pretty neat to be able to activate iterative calculation using gs4_create(). It makes the workflow easier to skip having to turn that on manually. My hope is that I can do the whole thing without leaving RStudio. 

The "to_gs_setup" differs between the two screenshots about only in whether gs4_formula() was used or not.  Here are screenshots of "column A" from my .Rmd notebook.

![image](https://user-images.githubusercontent.com/9826806/97031894-cfd0db80-1515-11eb-8231-5384bb2b4532.png)

![image](https://user-images.githubusercontent.com/9826806/97031912-d6f7e980-1515-11eb-839f-7e9f0da2561a.png)

Given that the formulas work if the leading ' marks are removed, I wondered if the issue has something to do with what gs4_formula is doing. I'm not a very sophisticated user, however. 

The last thing I'll mention for now is that I did try creating an empty spreadsheet with iterative calculation enabled, using gs4_create(), then using sheet_write() to load the data. That didn't make a difference.

Again, thank you. I will see if I can mock up a reprex and get the same behavior.

**Comment by nilescbn** [comment]
I came up with a simple example using circcular references. It runs fine. So the issue must have to do with my particular spreadsheet. 

Here's the example that will work. 

```
for_iter_calc <- tibble(
  account = LETTERS[1:5],
  sheet_rows = 1L:5L,
  category1 = gs4_formula(c("= 0.5 + 0.25*C3 + 0.125*C5",
                "= 0.6 + 0.2*C2",
                "= 0.2 + 0.1*C3",
                "= 0.35 + 0.3*C6",
                "= 0.7 + 0.1*C2"))
)

gs4_create("reprex iterative calc", 
           sheets = for_iter_calc,
           iterativeCalculationSettings = list("maxIterations" = 10000,
                                               "convergenceThreshold" = 0.00001))
```

**Comment by jennybc** [comment]
From a very cursory look, I already wonder if you might have a absolute vs relative reference problem?

I just know that when I was tinkering with formulas for, e.g. this vignette, I went to some trouble to make sure I was using relative references:

https://googlesheets4.tidyverse.org/articles/articles/write-sheets.html#write-formulas

It seems to be more cumbersome to do this in Sheets vs, say, Excel.

**Comment by nilescbn** [comment]
Thank you for the quick look and reply. I'm not terribly conversant in absolute vs relative references. This will be reason to finally try and learn. I will dig into that. 

And on being cumbersome, yes, guilty. My preference would be to do the iterative calculation within R. I'm sure there's some clever algorithim out there that I'm just not finding. Absent that, the export and reimport process with Sheets is much smoother than Excel, thanks to this package. 

Thanks again!

**Comment by jennybc** [comment]
> And on being cumbersome, yes, guilty

No, I was observing that writing formulas with relative references is harder (more verbose) in Google Sheets vs. in Excel. So no comment on you or me.

**Comment by nilescbn** [comment]
Okay, thanks for clarifying. I tried out the R1C1 syntax. As you allude to in the cellranger documentation, it does makes intuitive sense. Unfortunately, I couldn't get it to work. Sheets wasn't interpreting it correctly (or I'm doing it wrong). Yet I was getting error messages like this:

![image](https://user-images.githubusercontent.com/9826806/97061890-6240a180-154d-11eb-930f-7a2b37958525.png)

And that's for a cell where the only reference was to cell "R[561]C[0]". If I'm thinking about that correctly, it means "561 rows down, same column." If I had it backwards, and it's 561 rows up, then -779 doesn't make sense either... So a bit of a headscratcher.

Nonetheless, the good news is that the INDIRECT function is what I was missing. It's in your example, yet I wasn't clueing in to what that was. Using INDIRECT with the original A1 notation I had works. Here's a screenshot of "column A" converted with gs4_formula:

![image](https://user-images.githubusercontent.com/9826806/97061642-60c2a980-154c-11eb-9cc3-3c2f75fa0154.png)
 
So that's great, I'm excited to get it working. Thank you again and for all your efforts here and elsewhere in the tidyverse and R communities.

**Comment by jennybc** [comment]
So does that mean we can close this issue?

**Comment by nilescbn** [comment]
Sure, no objection here. Thanks again.
