### ISSUE TITLE
can gs4_create() be used with data frames containing more than 200,000 rows?

### ISSUE THREAD

**Issue by aaronmams** [tidyverse/googlesheets4#196]
I can't seem to use the gs4_create() function to move more than 200,000 rows of data. Here is the error I am receiving:

```{r}
n<-200000
> test.df <- data.frame(x1=rnorm(n),x2=rnorm(n),x3=rnorm(n),x4=rnorm(n),x5=rnorm(n))
> t <- Sys.time()  
> gs4_create("test-data3",
+            sheets=test.df
+ )
Creating new Sheet: "test-data3"
Error: Client error: (400) INVALID_ARGUMENT
  * Client specified an invalid argument. Check error message and error details for more information.
  * Invalid requests[0].updateSheetProperties: This action would increase the number of cells in the workbook above the limit of 5000000 cells.
```

What makes me suspect a row limitation somewhere is that I can successfully execute the same code with only slightly fewer rows:

```{r}
n<-180000
> test.df <- data.frame(x1=rnorm(n),x2=rnorm(n),x3=rnorm(n),x4=rnorm(n),x5=rnorm(n))
> t <- Sys.time()  
> gs4_create("test-data3",
+            sheets=test.df
+ )
Creating new Sheet: "test-data3"
> Sys.time() - t
Time difference of 3.207702 mins
> object.size(test.df)
7201224 bytes
```

And even trying to upload a data frame of much larger size (but fewer than 200k rows) doesn't seem to be problematic:

```{r}
n<-180000
test.df <- data.frame(x1=rnorm(n),x2=rnorm(n),x3=rnorm(n),x4=rnorm(n),x5=rnorm(n),
                      x6=runif(n),x7=runif(n),x8=runif(n),x9=runif(n),x10=runif(n))
t <- Sys.time()  
gs4_create("test-data3",
           sheets=test.df
)
Sys.time() - t
Time difference of 7.456010 mins
object.size(test.df)
12001904 bytes
```

I've read about Google's limitation of 5,000,000 cells (rows X columns) but my 200k rows by 5 columns wouldn't exceed this...also the "Client Error" makes me think this has something to do with me and not with Google.

It seems like my issue could be related to:

https://github.com/tidyverse/googlesheets4/issues/177

However, if the 40,000 new row cap were the issue, I think that all of my upload attempts should have failed. 

Any advice on how to fix (or further debug this)?

Thanks.

**Comment by jennybc** [comment]
I don't know. But I think it's a Sheets issue rather than googlesheets4 *per se*.

As for why it says you're violating the cell limit when you aren't. Either it's just a bug or ... maybe somehow the requested number of rows * the default of 26 columns gets created first, then pared down to your actual 5 columns? I really don't know.

But my advice would be to experiment with various ways of uploading the data in smaller pieces or initializing the Sheet, then updating it with bigger data.

If you're highly motivated, you could try doing the same task with the Python client to see if the result is different.

**Comment by aaronmams** [comment]
Thank you. I believe you are right that the issue is that a data frame with 200,000 rows and 26 columns would exceed the maximum number of cells allowed by Google Sheets. I tested this using:

```{r}
test.df <- data.frame(x1=rnorm(192300))
gs4_create("test-data",sheets=test.df)
```

and 

```{r}
test.df <-data.frame(x1=rnorm(192400))
gs4_create("test-data2",sheets=test.df)
```

The former eventually worked, while the latter produced the:

> Error: Client error: (400) INVALID_ARGUMENT
> * Client specified an invalid argument. Check error message and error details for more information.
>  * Invalid requests[0].updateSheetProperties: This action would increase the number of cells in the workbook above the limit of >5000000 cells

Noting that 192,300 * 26 < 5,000,000 and 192,400 * 26 > 5,000,000 makes me pretty convinced that your assessment is correct. 

I guess this isn't a really rigorous test but honestly I've found that anytime I try to create a sheet using gs4_create() with a data frame larger than about 30,000 rows I frequently encounter the server-side error:

> Error: Server error: (500) INTERNAL
>  * Internal server error. Typically a server bug.
>  * Internal error encountered.

So it's taken me a long time to reproduce the 400 error with data frames of various sizes.

Thank you very much for your attention and your great work on the tidyverse.

**Comment by jennybc** [comment]
I think you're operating at a Sheet size that really isn't the sweet spot for Google Sheets / spreadsheets in general (i.e. too much data). But I can certainly imagine how it's the best solution, all things considered, at a certain point in a project or for a certain project. So you'll just have to be a bit resourceful figuring out the best way to get the data in there.

**Comment by aaronmams** [comment]
Thanks again. This was more of a "just investigating what's possible" mission. The actual data I'm working with currently are multiple .csv files with ~ million rows and around 10 columns. It was easy enough to shove them into a MySQL database on a Google Cloud instance and connect to that from R/R Studio. For some SQL-averse colleagues I thought Google Drive/Google Sheets might be a little more approachable. 

From my view the ```googledrive::drive_upload()``` and ```googledrive::drive_download()``` functionality seems ok with these source data. I was wondering if ```googlesheets``` might be a better workflow since I could avoid making local copies of the data. But, as you pointed out, the size of the source data aren't really the sweet spot for Google Sheets.

**Comment by jennybc** [comment]
If you can do whole-file operations with the Drive API (and googledrive) that will be much more performant than using the Sheets API (and googlesheets4). I'm talking about writing/modifying. So perhaps you should use Drive to put the data there and Sheets to read it?
