### ISSUE TITLE
write_sheet errors when attempting to overwrite exisiting worksheet

### ISSUE THREAD

**Issue by rhamo** [tidyverse/googlesheets4#197]
With the (googledrive) package I use these functions to write a .csv file into my google drive daily which will overwrite the old .csv file and it works very well.

write.csv(dailydata,'dailydata.csv') x <- x %>% drive_update('dailydata.csv')
Now instead of writing a file into google drive am I able to overwrite a worksheet of an exisiting google sheet document daily?

I have installed the (googlesheets4) package and attempted the following functions with no success.

write_sheet(dailydata = "Reportmaster", sheet = "sheet2") Error: Auto-refreshing stale OAuth token. Error: Client error: (404) NOT_FOUND
Example: Google Sheet Documents name: "Reportmaster", work Sheet I would like to overwrite daily name: "sheet2".

**Comment by jennybc** [comment]
> write_sheet(dailydata = "Reportmaster", sheet = "sheet2")

`write_sheet()` does not have an argument named "dailydata". Please read the documentation on how to specify which Google Sheet you want to operate on.
