### ISSUE TITLE
write dataframe

### ISSUE THREAD

**Issue by mlamias** [tidyverse/googlesheets4#20]
I don't see any current capability to write a dataframe directly to google sheets without first writing to CSV.  Is this currently possible and if so how?  I can't seem to find the appropriate function to write a dataframe.  The previous version of googlesheets allowed users to issue gs_new() command, which was slow.  there does not appear to be a sheets_new() or a gs_new() equivalent.  Will this be implemented?

**Comment by aqsmith08** [comment]
+1 to this issue. It'd be great to have the ability to write a dataframe in R to an existing Google Sheet. Or, to append a dataframe in R to an existing Google Sheet.

**Comment by rixiren** [comment]
I note the "What’s yet to come? Writing to Sheets"  at https://googlesheets4.tidyverse.org/  

It would be great to know the expected horizon on this - if it's 2 months I will wait, if it's a year I will have to push on with the old googlesheets package. Could we possibly have a (loose) ETA?

**Comment by jennybc** [comment]
`sheets_create()` now does this -- but it's not ready for general use yet, as it always sends the data as character right now. But this is the beginning of rolling out the ability to write into Sheets.

**Comment by jennybc** [comment]
`sheets_write()` now does even more of this, but is also not ready for general use, as it also sends the data as character. But I'm closing this because I'll be opening more precise issues as I tackle refinements, like honouring col type.

**Comment by HadyShaaban** [comment]
Hello @jennybc 
I'm trying to export data to a google sheet using googlesheets4 but couldn't find a function for that
i tried sheets_write()
and also write_sheet() 
but couldn't solve the issue. Can you please help me in this issue with another function.

**Comment by jennybc** [comment]
This functionality exists only in the dev version and, as said above, is definitely not ready for general use. For example, it writes everything as character at the moment.

https://github.com/tidyverse/googlesheets4/blob/master/R/sheets_write.R

What version of googlesheets4 do you have?

**Comment by HadyShaaban** [comment]
i'm using googlesheets4 version : googlesheets4_0.1.0

**Comment by HadyShaaban** [comment]
but there is no method to upload my data to an existing googlesheet even using old googlesheets
that once trying to authenticate by package googlesheets,
the attached page appeared :)
![image](https://user-images.githubusercontent.com/31658534/70396428-9aacbf00-1a11-11ea-8c8e-fa989a5ecdca.png)

**Comment by jennybc** [comment]
The above looks like it pertains to the ORIGINAL googlesheets package, not this repository which is for the successor package googlesheets4

The default oauth app embedded in the original googlesheets package has been shutdown, so users have to provide their own:

https://github.com/jennybc/googlesheets/issues/397

**Comment by DannySmith100** [comment]
Hey there,
Do we have any update on when sheets_write() will be ready for general use?

**Comment by jennybc** [comment]
`sheets_write()` is in the dev version, which can be installed from GitHub, and I consider it ready for use. The only reason it has the "experimental" lifecycle label is become I'm not 100% happy with the function signature but also haven't found anything I like better.

There will be a CRAN release soon.
