### ISSUE TITLE
Can't get Google credentials after upgrading to R 4.0.3

### ISSUE THREAD

**Issue by ericcrandall** [tidyverse/googlesheets4#205]
Thanks for creating this package and Gargle - it has been huge for the project I'm working on.

I have exactly the same issue described here: https://github.com/tidyverse/googlesheets4/issues/27

Brief description of the problem

```r
gs4_auth(path = "path_to_my_jsonkey.json")
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html


gs4_auth_configure(path = "GEOME_credentials/geome-282803-0475069b49ce.json")
Error: Can't find 'client_id' and 'client_secret' in the JSON
```
There is a `client_id` in my JSON, but no `client_secret`

My json key is formatted thusly (redacted bits in square brackets):

```
{
  "type": "service_account",
  "project_id": "geome-282803",
  "private_key_id": "0475069b49ce95470acf65f5cecab1da96666f3e",
  "private_key": "-----BEGIN PRIVATE KEY-----\n [KEY TEXT] \n-----END PRIVATE KEY-----\n",
  "client_email": "[serviceaccount]@[serviceaccount].iam.gserviceaccount.com",
  "client_id": "[clientID]",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/[serviceaccount]%40[serviceaccount]iam.gserviceaccount.com"
}
```

`gs4_deauth() ` doesn't work, nor does renaming the folder at  `(~/.R/gargle)` However, if I do this, it will take me through the authorization process, and then still give me the error:

```r
gs4_auth("[email@gmail.com]")
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html
```

Any help would be appreciated!

**Comment by ericcrandall** [comment]
`> gargle::token_fetch(scopes = "https://www.googleapis.com/auth/spreadsheets", path = "GEOME_credentials/geome-282803-1d29ce24e220.json" )
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
NULL`

**Comment by ericcrandall** [comment]
OK, it is apparently working for someone else with a very similar setup to mine, so it is not an issue with gargle or google sheets4. Any help or suggestions still appreciated!

**Comment by ericcrandall** [comment]
One package, `askpass` needed updating to R v4, but none of the fail messages that I got from gargle or gs4 functions told me this. Just adding this for future reference by others.

**Comment by adomingues** [comment]
Thanks for the instructions @ericcrandall. In my case it was the package `httpuv` that was missing, but I only found out after running  `gs4_auth("[email@gmail.com]")`
