### ISSUE TITLE
Non-interactive service account token authentication not working

### ISSUE THREAD

**Issue by lpevzner** [tidyverse/googlesheets4#206]
Hello - Thanks for all your work on this package!

I seem to be having an authentication issue, when trying to set up non-interactive auth using a service account token. Wondering if this is a bug or I'm just missing something.

I created a service account token and stored it in a JSON file. I then used the following command:

```
gs4_auth (
   scopes="https://www.googleapis.com/auth/spreadsheets", 
   path="/Users/zwolfe/Documents/RScripts/svc_acct_token.json")
```

With `options(gargle_quiet = FALSE)`, I see the following:

```
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
service account email: email_address@project.iam.gserviceaccount.com
```
Everything seems to work!

But when I try to run `gs <- gs4_find(my_sheet_name)`, I get the following:

```
attempt from: googledrive
trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token
```
...And then it opens up a browser window, asking me to log into my account.
Seems like `credentials_service_account()` succeeds the first time around, but then it gets invoked again and it fails. Is this a bug or am I missing something here?

Thanks in advance!

**Comment by jennybc** [comment]
> attempt from: googledrive

googledrive is NOT going to use the token you just loaded up for Google Sheets / googlesheets4. They have different scope needs. I suspect you need to ponder this article about using Google Drive / googledrive and Google Sheets / googlesheets4 all at the same time.

https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html

**Comment by jennybc** [comment]
That article is aimed at the person using web-flow type of OAuth, but the basic principles apply to you and your service token too.

**Comment by lpevzner** [comment]
Ah! I see, I was wondering why it said "attempt from: googledrive". Didn't realize gs4_find was a wrapper around a drive function. That makes a lot of sense. 

Thank you so much for the quick response!

This is now resolved. I ended up just hardcoding the Google Sheet IDs into my script instead of using gs4_find to do a name lookup, thereby avoiding use of googledrive altogether. Decided that's sufficient for my purposes. Thank you again for your help!

**Comment by jennybc** [comment]
> Didn't realize gs4_find was a wrapper around a drive function

This is documented but it is still a "gotcha":

https://googlesheets4.tidyverse.org/reference/gs4_find.html

> hardcoding the Google Sheet IDs into my script instead of using gs4_find to do a name lookup

Yes, if your usage supports this, it is definitely the more robust and minimal approach.
