### ISSUE TITLE
Refresh Sheet

### ISSUE THREAD

**Issue by johnbde** [tidyverse/googlesheets4#207]
Thanks a ton for the great package. I have a google sheet which has several today( ) functions which is used to pull data from google finance. Since it has several today( ) functions, it takes a few seconds to load the returned values from googlefinance( ). Just wondering if this package has any function to refresh or reload the sheet from R. I found this `gs4_browse("xxxxxx")` useful but can we close the sheet from R after visiting the sheet in browser?

**Comment by jennybc** [comment]
Is the data for cells containing `today()` cells incorrect when you use `read_sheet()`?

More specifics would aid this conversation in terms of what you these formulas look like, what your doing in googlesheets4/R, and how that is or is not matching expectations.

https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html

**Comment by johnbde** [comment]
Thanks. No it is not incorrect but it returns nothing (blank) as googlefinance( ) function takes a few seconds to return values. So I need to manually open the sheet so that today( ) cells get loaded, then when I read data in R, it works fine. See some of the examples of formulas below -
`=GOOGLEFINANCE("NSE:RELIANCE", "price")
`
The below function is computationally intensive so takes a few seconds to return values
`=(M2-Index(QUERY( GOOGLEFINANCE(B2,"close",TODAY()-8,TODAY(),"daily") , "select Col2 limit 6", 1),4,1))/Index(QUERY( GOOGLEFINANCE(B2,"close",TODAY()-8,TODAY(),"daily") , "select Col2 limit 6", 1),4,1)
`

**Comment by johnbde** [comment]
Wanted to highlight an important point regd. the sheet, calculation in the sheet is set "On change and every minute"

**Comment by jennybc** [comment]
I was about to paste this link about Spreadsheet properties accessible to the API:

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#RecalculationInterval

But if you've already got it set to recalculate every minute, I'm not sure what to say.

**Comment by johnbde** [comment]
Thank you for your prompt response. Is RecalculationInterval available in googlesheets4 package?

**Comment by jennybc** [comment]
> Is RecalculationInterval available in googlesheets4 package?

It's not explicitly exposed in a high-level function but there is a mechanism for sending arbitrary metadata. In this example, I set a new Sheet's locale and time zone:

https://googlesheets4.tidyverse.org/articles/articles/write-sheets.html#write-metadata

So you could experiment with `RecalculationInterval`. If memory serves, I've only exposed that at Sheet creation time and haven't offered a way to modify such a property of an existing Sheet. I could do that if we discovered an actual use case for it.
