### ISSUE TITLE
Trouble with OAuth

### ISSUE THREAD

**Issue by jasonboots** [tidyverse/googlesheets4#209]
I've been running googlesheets4 on out Windows server without error since March and suddenly, think just stopped authorizing for our oauth tokens (this actually happened across googsheets4, googledrive and gmailr). We have started to get the following error (even while in an interactive session in RStudio):

Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html

To troubleshoot (in RStudio), I update rlang, gargle, gmailr, googledrive and googlesheets4. This made no change. I used both base::interactive() and rlang::is_interactive() to double check I was still operating as an interactive session (both return TRUE). I've tried calling gs4_auth(), drive_auth() with and without the email and with and without the use_oob=TRUE with no change.

I do run service accounts for most of our things using a .json file and those seem to be working without fail still, but some of the file writing in gdrive and the handful of automated email just simply must happen from a non-service account. I feel like I'm taking crazy pills. What else can I try?

**Other details:**
Windows 10
R version: 3.6.3
Rstudio version: 1.4.1103
gargle version: 0.50
gmailr version: 1.0.0
goosglesheets4 version: 0.2.0
googledrive version: 1.0.1

**Code and output** (after turning gargle options verbose):
library("googlesheets4")
gs4_auth("myuser@myoragnization.org")
trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googlesheets4
adding 'userinfo.email' scope
loading token from the cache
Error: error reading from connection
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by jennybc** [comment]
General troubleshooting ideas are in:

https://gargle.r-lib.org/articles/troubleshooting.html

This advice in particular seems relevant:

> It is relatively harmless to delete the folder serving as the OAuth cache. Or, if you have reason to believe one specific cached token is causing you pain, you could delete a specific token (an .rds file) from the cache. OAuth user tokens are meant to be perishable and replaceable.

**Comment by jennybc** [comment]
It sounds like you've maybe run up against something like this:

> A specific Google user (email) can only have a certain number of OAuth tokens at a time (something like 50 per OAuth client). So, whenever you get a new token (as opposed to refreshing an existing token), there is the potential for it to invalidate an older token. This is unlikely to have any practical effect for a normal user, but can be noticeable for someone developing against a Google API or someone working from many different machines / caches.

Which underscores why it's good that you use service accounts a lot. I'd advise shifting as much as you can to service accounts, when appropriate and possible.

**Comment by jasonboots** [comment]
Thanks Jenny. I hadn't seen that Gargle troubleshooter before, so I will hop into that to see what I can find.

I woudl highly doubt the issue is a token limit since the issue is affecting all users and happened simulatneuosly with all of our accounts. 

I will follow up with solution or more details after working through the gargle trouble-shooting.

**Comment by jennybc** [comment]
Do you all have some sort of Google GSuite thing and could an administrator have changed a policy? I.e. re: granting the tidyverse app permission to get tokens?

**Comment by jasonboots** [comment]
Interesting...it seemed like it wasn't connecting to the oauth cache:

> gargle_oauth_sitrep()
gargle OAuth cache path:
C:/Users/myuser/.R/gargle/gargle-oauth
Error in FUN(X[[i]], ...) : error reading from connection

There were 4 tokens in the folder at the time dating back to 2/18/21 (last time our codes had run properly).

I dropped a csv in the folder really quickly and used read_csv to ensure folder permissions hadn't somehow gotten boggled up and the csv read successfully. 

After that I deleted the tokens that I could tell were associated with my google account and went in a tried again with gs4_auth(). Voila, it took me to the interactive authentication as expected and loaded a new token in the cache (that is appropriately called in the non-interactive sessions thereafter).

So...in the sense that I have resolved my issues we could close this. Given what happened withgargle and the tokens that were in there and the errors it returned, I would leave that up to you decide whether or not there are any small details you'd want to clean up in your next update of things.

To you question about gsuite: I had asked our gsuite administrator if they had made any changes in the past two weeks and they said no. I do however suspect that something must have happened oragnization-wide to invalidate all of our oauth tokens at the same time.

Thank you so much for all of your work keeping this package going and responding to all of the issues even when it is mostlikely user error :)

**Comment by jasonboots** [comment]
Sorry...one additional note about th gargle behavior in case it is releveant or matters to you:

After interactively creating my token, I did re-run gargle_oauth_sitrep() with th result being the single token I had just created (nothing about the other two tokens that remained in there).

**Comment by jennybc** [comment]
> Given what happened withgargle and the tokens that were in there and the errors it returned, I would leave that up to you decide whether or not there are any small details you'd want to clean up in your next update of things.

At the moment, I don't have anything concrete enough to merit a change. I'd say we still don't know why this happened in your organization. Are these tokens on personal computers or on a server? It almost feels like the files got corrupted.

> After interactively creating my token, I did re-run gargle_oauth_sitrep() with th result being the single token I had just created (nothing about the other two tokens that remained in there).

I'd delete these leftover tokens that seem unusable. I don't understand what happened here, but the fact remains that OAuth tokens should be regarded as semi-perishable and for someone reason you just got forced to spring clean.

**Comment by jennybc** [comment]
I'm going to conclude that this is somehow specific to your GSuite organization or something else about your organization's environment.
