### ISSUE TITLE
Authentication is not possible anymore

### ISSUE THREAD

**Issue by paulvern** [tidyverse/googlesheets4#211]
I had many apps working greatly with this awesome package and Shiny till... today.
At the moment, after the authentication, Google blocks the app completely. Is there any workaround?
Thanks.

**Comment by jennybc** [comment]
I can use the package fine right now, with auth.

The above contains no information useful for troubleshooting.

**Comment by paulvern** [comment]
Probably my mistake then. I've been using a saved token.
In order to save the token locally I just wrote two simple lines:
```
tokenizza <- gs4_token()
saveRDS(tokenizza,file="token.rds")
```

then I reuse it in Shiny login with:
`gs4_auth(token=tokenizza)`

But the process hangs there.

**Comment by jennybc** [comment]
The package that powers auth for googlesheets4 and several other Google-y package is called gargle. It sounds like this troubleshooting section is a good place to start:

https://gargle.r-lib.org/articles/troubleshooting.html#gargle_oauth_sitrep

Especially this part might be relevant:

> If you have rigged some remote mission critical thing (e.g. a Shiny app or cron job) to use a user OAuth token (which is not a great idea), one day continued acquisition of new tokens in your normal interactive life will invalidate the mission critical token. Your thing (the Shiny app or cron job) will mysteriously fail because the OAuth token can’t be refreshed. Be prepared to deal with that periodically or, better yet, upgrade to a more robust strategy for non-interactive auth.

**Comment by paulvern** [comment]
Sadly, I'm using opencpu (https://www.opencpu.org/) along with my R code and it doesn't provide any way to authorize the app interactively (a thing I can manage to do with a Shiny app by logging with `googleAuthUI("loginButton")`). So my code at the moment looks like this:
 google_app <- httr::oauth_app(
    "my app name",
    key = "mykey-3rk6bdj1fqp38d3olqnnbgl5qkk8ch9b.apps.googleusercontent.com",
    secret = "mycodeTxuplxZSlTHPS5Qz1HG_B"
  )
google_key="mygooglekey-EzkxeKKZBXE"
 drive_auth_configure(app = google_app,api_key=google_key)
 drive_oauth_app()
 drive_api_key()
 drive_auth(scopes="https://www.googleapis.com/auth/drive")

Still, the login process fails.

I tried also by downloading the .json secret files from my google console and I tried the authorization  by typing:
`drive_auth(path="/home/mydir/temp/secret.json")`
Still, Google doesn't allow me to login.

**Comment by jennybc** [comment]
If you want to power a Shiny app with a user OAuth token, which is not a great idea, as described above, you have to create that token in a legitimately interactive environment. Then move it to the server.

And you need to be prepared to re-do this when the old token stops refreshing, i.e. has somehow become invalid.

**Comment by jennybc** [comment]
I think if you need to re-make your token (or switch to a service account token), this will be resolved and will optimistically close this. I would also make sure you're using the same versions of googlesheets4 and gargle locally and on the server.

You should also probably read https://github.com/tidyverse/googlesheets4/issues/218#issuecomment-792311562, in case the credential roll is also part of your experience. But your vulnerability to us rolling the OAuth app is one of the signals that you should either be creating the token with your own app or not using an OAuth user token. Or you need to be prepared to remake this token, sync package versions, and re-upload to the server at any time.
