### ISSUE TITLE
No `client_secret` field in service account JSON

### ISSUE THREAD

**Issue by ajjitn** [tidyverse/googlesheets4#212]
Thanks for this great package! I tried following the instructions in the `Service Account token` section of the Get Api credentials [vignette](https://gargle.r-lib.org/articles/get-api-credentials.html) for generating a service account. This is the structure of the JSON file I downloaded from the GCP console.

```
{
  "type": "service_account",
  "project_id": "some-project",
  "private_key_id": "123456ffff123456",
  "private_key": "-----BEGIN PRIVATE KEY-----\nrandomlongRSAstringofletters\n-----END PRIVATE KEY-----\n",
  "client_email": "service-account-name@some-project.iam.gserviceaccount.com",
  "client_id": "1234566",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/project-name%40some-project.iam.gserviceaccount.com"
}

```

After moving the JSON into my project directory, I tried running `gs4_auth_configure(path="google_key_name.json")`, but I get the following error:

```
#> Error: Can't find 'client_id' and 'client_secret' in the JSON
```

And indeed, the `client_secret` field does not exist in the JSON downloaded from Google. Am I incorrectly generating a service account JSON? Or has the structure of the JSON object changed recently? Any help you could provide would be great! For context, I'm hoping to authenticate with a service account as I want to use `googlesheets4` in non-interactive authentication context. My `sessionInfo` is below if that's helpful

```{r}
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets4_0.2.0

loaded via a namespace (and not attached):
 [1] assertthat_0.2.1  crayon_1.4.0      dplyr_1.0.3       cellranger_1.1.0 
 [5] R6_2.5.0          jsonlite_1.7.2    DBI_1.1.1         lifecycle_0.2.0  
 [9] magrittr_2.0.1    pillar_1.4.7      rlang_0.4.10      fs_1.5.0         
[13] vctrs_0.3.6       generics_0.1.0    ellipsis_0.3.1    tools_4.0.3      
[17] googledrive_1.0.1 glue_1.4.2        purrr_0.3.4       compiler_4.0.3   
[21] gargle_0.5.0      pkgconfig_2.0.3   tidyselect_1.1.0  tibble_3.0.6     


```

**Comment by jennybc** [comment]
You're confusing 2 different types of JSON file:

* Service account token. Provide the `path` to this as an argument to `gs4_auth()`. (Or rig it up so the Application Default Credential search strategy finds it https://gargle.r-lib.org/reference/credentials_app_default.html)
* OAuth app, which is 1 leg of the 3 legs of "three-legged oauth". Provide the `path` to this as an argument to `gs4_auth_configure()`.

You want and have 1 but you're doing 2.

**Comment by ajjitn** [comment]
As expected, a silly mistake on my part! I'll go ahead and close the issue, thanks Jenny!

**Comment by jennybc** [comment]
Oh, you are not the first nor, I'm sure, the last.

**Comment by ajjitn** [comment]
One other thought I had after debugging a bit more: When I first used the `path` argument in `gs4_auth`, my JSON was slightly malformed (my fault) and the function silently reverted to using interactive authorization through the browser. It would be helpful to have a warning message in `gs4_auth` (or perhaps more accurately the underlying `gargle::token_fetch` function) when the service account JSON provided to the `path` function is malformed/not used.

**Comment by jennybc** [comment]
The intended troubleshooting there is for someone to toggle `gargle_quiet` and get all sorts of info on how the token fetching process is going:

https://gargle.r-lib.org/articles/troubleshooting.html#gargle_quiet

**Comment by ajjitn** [comment]
The best feature requests are the ones that have already been built!
