### ISSUE TITLE
xdg-utils is required to open the authentication link

### ISSUE THREAD

**Issue by YlanAllouche** [tidyverse/googlesheets4#223]
I am not sure if this is inherited from Gargle and I could not find the code responsible for this behavior.
On a system without xdg-utils (minimal container or OS), R will still try to open the link with xdg-open.

The easiest to repro this would be with Rocker's containers.
First obtain a new session with: `docker run -it --rm rocker/tidyverse`
In R:
```r
install.packages("googlesheets4")  
library(googlesheets4)
gs4_auth()
```
returns:

```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
sh: 1: xdg-open: not found
```

Ideally, a link would be printed in terminal to copy in a browser manually if xdg-open is not found in $PATH and/or would try using $BROWSER if it exists.

**Comment by YlanAllouche** [comment]
It looks like xdg-utils also looks at $BROWSER in last resort.

Setting $BROWSER to `echo` does not print the URL. I suppose it creates a new thread.

I tried setting $BROWSER to a one line script that would output to R's PID:

```bash
echo "$@" > /proc/$RPID/fd/1 & 
```

while in R, I set $BROWSER and RPID:
```r
Sys.setenv(BROWSER = "/echo-browser.sh")
Sys.setenv(RPID = Sys.getpid())
```

The only issue now beyond having to ship xdg-utils for printing a URL in terminal is that after the URL does print gs4_auth seems stuck and does not give me the opportunity to paste the link from the API.

**Comment by obarisk** [comment]
Are you running a non interactive login?

https://cran.r-project.org/web/packages/gargle/vignettes/non-interactive-auth.html

**Comment by YlanAllouche** [comment]
I'm not sure if non-interactive has some special meaning in this context but:
- interactive() returns TRUE
- I send commands 1 by 1 in an interactive R shell

I understand how to provide gs4::auth a gargle directory and an email for "unattended" token refresh.
It's more about being able to generate that token on a server on minimal install in the first place. 
That would also help our non-R user run our R applications by easily generating the gargle file.

**Comment by jennybc** [comment]
This behaviour is coming all the way from httr (via gargle), i.e. what the auth dance looks like in the case of out of bound auth.

**Comment by YlanAllouche** [comment]
Any chance you can think of a fix even if it doesn't come out of gargle/googlesheets4?
the solution I proposed by setting $BROWSER could work if I knew what kind of signal I would need to send to make R interactive again.

**Comment by jennybc** [comment]
Here are the relevant code paths for initial token acquisition in the out of bounds auth context:

https://github.com/r-lib/httr/blob/80cb625117629105874d58a234f061b458eefbe6/R/oauth-exchanger.r#L14
https://github.com/r-lib/httr/blob/80cb625117629105874d58a234f061b458eefbe6/R/http-browse.r#L15

So you eventually hit `utils::browseURL()`:
https://rdrr.io/r/utils/browseURL.html

Have you tried setting the environment variable `R_BROWSER`?

**Comment by YlanAllouche** [comment]
Thanks a lot, that's very good to know.
Do you have an idea what I could set the BROWSER to simply print the url in tty?

**Comment by jennybc** [comment]
I think you'd be better off intercepting things by setting the R `"browser"` option:

``` r
withr::with_options(
  list(browser = function(url) cat(url, "\n")),
  browseURL("yo")
)
#> yo
```

<sup>Created on 2021-05-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by YlanAllouche** [comment]
It does print the URL but I still don't get the interactivity of the R shell back even with `\n`.

**Comment by jennybc** [comment]
Backing up a little, I think you should be requesting out of band auth, but I realize now you haven't mentioned or shown that you are.

Meaning: `drive_auth(use_oob = TRUE)`. Or set the option `gargle_oob_default` or the option `httr_oob_default` to `TRUE`.

**Comment by YlanAllouche** [comment]
It still either doesn't print the link or does not let me paste the code.

For now, I understand the authorization Google API link link for "tidyverse" doesn't change. I could always provide that and `googlesheets4::gs4_auth(use_oob = TRUE)` does let me paste the code even through it never prints the link.

**Comment by jennybc** [comment]
I think I have brought you as far as I can. As I said, this is really beyond the reach of googlesheets4 and even gargle. I suppose you have your reasons for working in such a minimal container, but it certainly brings challenges. Your other alternative is to work from such a container with another method of auth, i.e. service account token or application default credentials, which does not require any interaction.

**Comment by obarisk** [comment]
Here are the workarounds for this issue

1. mount xdg-open to the container

```bash
docker run -it -v /usr/bin/xdg-open:/usr/bin/xdg-open --rm rocker/tidyverse
```
2. change the browser option

```r
writeLines(r"(#/usr/bin/env bash 
echo -n "\n"
echo -n "$@" >&2
exit 2                                                                                                                                                                                                           )", "browser.sh")
Sys.chmod("browser.sh", mode="755")
options(browser="./browser.sh")
library(googlesheets4)
gs4_auth(use_oob=T) 
```

Juse follow this one. https://github.com/tidyverse/googlesheets4/issues/223#issuecomment-832914516
and check out the source code of utils::browseURL

in utils::browseURL
it's a system call. and redirect stdout to /dev/null.

**Comment by jennybc** [comment]
Glad you found a solution!
