### ISSUE TITLE
Authenctication Completed but can't get credentials

### ISSUE THREAD

**Issue by johnbde** [tidyverse/googlesheets4#225]
Thanks for this lovely package. Today drive_auth() is unable to get google credentials even after authentication is completed. I can see  **Authenctication Complete** in the console and browser as well. My code has been working for last 6 months, today it suddenly stopped working. I am using R version 4.0.5 and googlesheets4 0.3 version

#> Error: Can't get Google credentials.
#> Are you running googledrive in a non-interactive session? Consider:
#>   * `drive_deauth()` to prevent the attempt to get credentials.
#>   * Call `drive_auth()` directly with all necessary specifics.

**Comment by jennybc** [comment]
Closing due to lack of follow up.
