### ISSUE TITLE
Non-interactive access to google drive

### ISSUE THREAD

**Issue by SebastianJHM** [tidyverse/googlesheets4#227]
Hola otra vez.
Logré crear mi cunta de servicio para la API de Sheets y logré darle autorización a mi Spreadsheet para poder acceder a ella conla llave, eso funcionó bien.
Ahora me encuentro atascado con googledrive, puesto que intento usar el mismo archivo json para acceder de forma automatica, pero no se como indicarle  a mi cuenta de google drive que voy a acceder con las credenciales.

**Comment by cpilat97** [comment]
Hi again @SebastianJHM, 

(just want to note that i don't know much spanish and was using google translate for your message. hoping i got everything right)

Jenny [pointed me to this resource](https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html) when I opened a separate [issue](https://github.com/tidyverse/googlesheets4/issues/224) and was using both googledrive and googlesheets4 packages.  You have to be sure to authorize both packages. Just calling the auth on one doesn't authorize the other with the service account. 

The gist would be to auth on googledrive first and then auth on googlesheets4. 
i.e. 
```R
  drive_auth(path = "path/to/service-account-key.json") #then there are two ways you can do gs4_auth:
  gs4_auth(path = "path/to/service-account-key.json") #explicitly stating the path to the key again OR:
  gs4_auth(token = drive_token()) #this uses the token stored from the drive_auth call

````

Hope this is helpful!

**Comment by SebastianJHM** [comment]
@cpilat97 Thank you. I am trying this:
```r
library(googlesheets4)
library(googledrive)
gs4_auth(
    scope = "https://www.googleapis.com/auth/drive",
    path = "./XXXXXXXXXXXXXXXXXXXXXXXXXX.json"
    )
drive_auth(token = gs4_token())
```
This work in order to read the id of documents but I can't create folder or copy and paste files.

**Comment by jennybc** [comment]
The basic approach above looks correct @SebastianJHM.

Can I see the exact failure? Meaning EXACTLY what do you see when you try to "create folder or copy and paste files".

These instructions are for googlesheets4, but the basic ideas for how to make a reprex hold for googledrive as well:
https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html

Remember, this service account is not formally connected to you as an individual, so I suspect the disconnect is perhaps that you expect it to be operating freely on *your* My Drive, whereas it operates on *its* My Drive.

**Comment by SebastianJHM** [comment]
My problem is that I still can't point to my google drive although I can point to the spreadsheets 
```r
library(googlesheets4)
library(googledrive)
gs4_auth(
    scopes = "https://www.googleapis.com/auth/drive",
    path = "XXXXXXXXXXXXXXX.json",
    cache = ".secrets"
    )
drive_auth(token = gs4_token())


ss <- "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
read_sheet(ss)
# Reading from "MyFile"
# Range "Hoja 1"
# # A tibble: 7 x 4
# a     b     c     d
# <dbl> <dbl> <dbl> <dbl>
#     1     2     2     2     2
# 2     3     3     3     3
# 3     4     4     4     4
# 4     5     5     5     5
# 5     6     6     6     6
# 6     7     7     7     7
# 7     8     8     8     8

df <- data.frame(
    "a" = 1,
    "b" = 2,
    "c" = 3,
    "d" = 4,
)


sheet_append(ss, data = df, sheet = 1)
# Writing to "MyFile"
# Appending 3 row(s) to "Hoja 1"


googledrive::drive_find("MyFile")
# # A tibble: 1 x 3
# name   id                                           drive_resource   
# * <chr>  <chr>                                        <list>           
#     1 MyFile 1FT3vDBIgorsTW-BUGnLmbz7XuxQJ_P-2E0IbnhNi6ug <named list [35]>



## Copy MyFile in a exiting folder x
googledrive::drive_mv(file = "MyFile", path = "~/x/MyFishFile")
# Error: Parent specified via `path` does not exist


googledrive::drive_mkdir("~/OtherFolder")
# Created Drive file:
#     * OtherFolder: 1vTONR8D-aJ30pTcknuYdAOSS0bSf1JDK
# with MIME type:
#     * application/vnd.google-apps.folder

## Not appear folder in my drive
```

**Comment by jennybc** [comment]
You should remove this line, as it is irrelevant when using a service account token and will just lead to confusion:

```
cache = ".secrets"
```

I would take this message at face value:

```
## Copy MyFile in a exiting folder x
googledrive::drive_mv(file = "MyFile", path = "~/x/MyFishFile")
# Error: Parent specified via `path` does not exist
```

Apparently the relevant user's My Drive (**the service account**) does not have a folder named `x`.

```
googledrive::drive_mkdir("~/OtherFolder")
# Created Drive file:
#     * OtherFolder: 1vTONR8D-aJ30pTcknuYdAOSS0bSf1JDK
# with MIME type:
#     * application/vnd.google-apps.folder

## Not appear folder in my drive
```

As I say just above and in the message before that, you need to appreciate that your are auth'ed as the **service account**. And files created in the top-level My Drive of the service account will not appear in your personal My Drive.

**Comment by SebastianJHM** [comment]
So there is no way to access and manipulate my drive from a service account?

**Comment by jennybc** [comment]
> So there is no way to access and manipulate my drive from a service account?

No, not your "My Drive", because you are literally authenticating as an entirely different user, i.e. as the service account. It is possible, with support from a Google Workspace admin at your organization, to use domain-wide delegation of authority to do this:

https://developers.google.com/admin-sdk/directory/v1/guides/delegation

But I must say I have never done it.

If I recall, your use of a service token originates from #226:

> My intention is to write a shiny application that writes data in a spreadsheet ... I would like to know how to fill the gs4_auth () to be able to read and write in the spreadsheet. I should clarify that I would like only the application to have the permissions to access the data.

The usage you describe there is a perfect fit for a service token. It's narrow (deals with one specific Sheet), it's machine to machine, etc.

Here in this thread, you seem to be trying to do *other general stuff*, on behalf of your user account, via a service account, which simply won't work (without domain-wide delegation).

**Comment by jennybc** [comment]
This thread seems to have trailed off and its definitely about usage, not a bug. Further discussion would be best suited to somewhere like https://community.rstudio.com.
