### ISSUE TITLE
occasional curl::curl_fetch_memory error in read_sheet

### ISSUE THREAD

**Issue by lotard** [tidyverse/googlesheets4#233]
Sometimes, and I really cannot pinpoint when (not specifically upon token refresh), this error will appear when running read_sheets:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Error in the HTTP2 framing layer
```
Rerunning the same code immediately usually doesn't error and everything is fine, till the next, random time it happens. Maybe related to #123.

Could be useful to catch it and try again, because that'll resolve it 99% of the time in my case.

**Comment by jennybc** [comment]
This is definitely beyond the scope of googlesheets4 or even gargle.

https://github.com/jeroen/curl/issues/156#issuecomment-492563623
https://cran.r-project.org/web/packages/curl/vignettes/intro.html#disabling_http2

FWIW, I have this in my `.Rprofile`, because of this exact reason.

``` r
...

  # experiment to see if this solves the HTTP/2 framing layer errors that have
  # become common for me with Google (August 2020), probably due to my
  # switch from Mojave to Catalina (or, more specifically, the associated
  # version change in libcurl)
  # https://github.com/jeroen/curl/issues/156#issuecomment-492563623
  # https://cran.r-project.org/web/packages/curl/vignettes/intro.html#disabling_http2
  if (requireNamespace("httr", quietly = TRUE)) {
    # '2' is the enum value corresponding to CURL_HTTP_VERSION_1_1
    httr::set_config(httr::config(http_version = 2))
  }

...
```
