### ISSUE TITLE
Potential Feature Request: read_sheet by worksheet id 

### ISSUE THREAD

**Issue by cpilat97** [tidyverse/googlesheets4#234]
Hi Jenny!! 

Wanted to raise a potential feature request (if it's not already something in the works/something that may be possible): 

Using the tab/worksheet id as a third way to identify which sheet a user may want to pull data from. 

The [current docs ](https://googlesheets4.tidyverse.org/reference/read_sheet.html) for read_sheet() function state a user can either use the Sheet Name or the Tab Index number to identify the sheet to read. 

An example of what i'm thinking: 

```r
library(googlesheets4)

#using gapminder url: 
#https://docs.google.com/spreadsheets/d/1U6Cf_qEOhiR9AZqTqS3mbMF3zt2db48ZP5v3rkrAEJY/edit#gid=780868077

ss_gapminder <- gs4_get("1U6Cf_qEOhiR9AZqTqS3mbMF3zt2db48ZP5v3rkrAEJY")

#normal way to read in Africa tab
africa_data <- read_sheet(ss = ss, sheet = "Africa") 

#what i'm kind of thinking of: 
africa_data <- read_sheet(ss = ss, sheet = 780868077) #or 
africa_data <- read_sheet(ss = ss, gid = 780868077) #or
africa_data <- read_sheet(ss = ss, sheet_id = 780868077)

#i do see the worksheet id's in the data that's grabbed from the gs4_get() call if i run: 
ss_gapminder[["sheets"]][["id"]]
```

An issue on this i'm already seeing is that the sheet arg accepts numbers, and when it receives a number, it looks for that sheet. Obviously the spreadsheet won't have a sheet number of 780868077. And if we were to wrap 780868077 in quotes, the sheet arg would look for a sheet with the name of "780868077". 

I'm not sure if gid could be an additional argument? 

For additional context (sorry for making this so long), I work in a large org (NYC Department of Education) where google sheets is heavily utilized across many departments and users. I scrape a lot of the data between many teams to make data reports, etc... While it's not constant, there are the occasional folks that change sheet names or positions depending on how their job changes and, since many of them are not data folks, they don't think much of it. But then that breaks scripts that rely on the names/tab positions. 

The worksheet id might be more stable, correct? I haven't seen that change even when changing tab names or tab position. I tried doing some searching through the issues on googlesheets4, did some googling, stackoverflow, but most of my searches bring me to the sheet id, not the worksheet id. 

Would love to hear your thoughts on this. 

Thanks so much for all your work on this package! It's been an absolute game changer for my work. 

Cory

**Comment by jennybc** [comment]
Yes I understand what you're getting and I agree. I basically consider this as covered by #88, but this issue provides useful context and detail. I'm going to close this in favour of #88, but now they are linked and when I tackle #88, I'll take this input into account.
