### ISSUE TITLE
Using googlesheets4 together with github actions without gs4_deauth

### ISSUE THREAD

**Issue by relund** [tidyverse/googlesheets4#236]
Someone who have hints on using the package with github actions to access a private google sheet?

**Comment by jennybc** [comment]
This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio Community](https://community.rstudio.com).

---

Other suggestions: googlesheets4 itself uses an encrypted service account token in its tests and this set up is documented in a gargle article:

https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html

The gmailr package uses a user token in its tests:

https://github.com/r-lib/gmailr

In general, you could probably turn up other examples of people doing googlesheets4 or similar auth in GHA by doing some targeted GitHub searches.
