### ISSUE TITLE
Download Sheet into PDF

### ISSUE THREAD

**Issue by briandpassa** [tidyverse/googlesheets4#239]
Hi, thank you for the great library. 

In googlesheets library, there is a gs_download function to download a pdf of a sheet. What's the best way to accomplish this in  googlesheets4 library?

**Comment by jennybc** [comment]
This is now a job for the googledrive package. googlesheets (the original package) was a mash up of wrappers around the Sheets and Drive APIs. The current division of labor is that googledrive does all Drive work and googlesheets4 does (only) spreadsheet specific stuff.

Use `googledrive::drive_download()`.

``` r
library(googledrive)

# I'm downloading a public Sheet, so I don't need auth.
drive_deauth()

x <- drive_example_remote("chicken_sheet")

drive_download(x, path = "chicken_sheet.pdf")
#> File downloaded:
#> • 'chicken_sheet' <id: 1SeFXkr3XdzPSuWauzPdN-XnaryOYmZ7sFiUF5t-wSVU>
#> Saved locally as:
#> • 'chicken_sheet.pdf'
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

More resources that will be helpful:

https://googledrive.tidyverse.org/reference/drive_download.html

https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html
