### ISSUE TITLE
Wire up for auth

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/googlesheets4#24]
From `?read_sheets`:

> *Note that googlesheets4 is not wired up for auth yet (happening soon!)*, so at the moment the target Sheet must be readable by anyone with a link (see examples for how to accomplish via googledrive).

It would be marvellous to have auth support for use in the workplace.

A workaround is to export the file with `googledrive` as `.xlsx` and import with `readxl`, but this of course isn't necessarily equivalent.

```r
library(googledrive)
library(readxl)

drive_file <- drive_get(id = "gObbleDEgooK")
local_file <- drive_download(drive_file, path = tempfile(fileext= ".xlsx"))
sheet <- read_excel(local_file$local_path)
```

**Comment by leerssej** [comment]
Found a way to use only googledrive and csv's:

```
library(googledrive)

drive_get("my_googsheet", team_drive = 'Data Team') %>%
  drive_download("~/Downloads/gs_temp",  type = "csv", overwrite = TRUE)
```

**Comment by leerssej** [comment]
It is now wired up c/o of `gargle` (and `httr`).
Please see here for further information: https://github.com/tidyverse/googlesheets4/issues/27#issuecomment-507011452

**Comment by jennybc** [comment]
This package has been using gargle for a while. And as of 094063ee2ddb4b2e6bb0e9406c4482a96de0462b it's working with the version of gargle on CRAN. So this is done.
