### ISSUE TITLE
read_sheet() drops $ from some values [reprex dataset with 15 rows]

### ISSUE THREAD

**Issue by charliejhadley** [tidyverse/googlesheets4#249]
Steps to replicate:

1. Add this data to a google sheet (or use [this template sheet](https://docs.google.com/spreadsheets/d/1IA3q8qJOEumbQQwyHvQHecSBoFh1ndtWjb1JKSVXOPA/edit?usp=sharing))

| col_a |
|  :-- |
|  48000|
|40000|
|$15,000|
|$41,715|
|$20,857|
|$10,429|
|$52,143|
|$26,072|
|$41,714|
|$78,215|
|51,000|
|$50,000|
|$15,643-26,07|

2. Read in the data and collapse the <list> column with `as.character()`

```r
library(googlesheets4)
g_data <- read_sheet("https://docs.google.com/spreadsheets/d/1IA3q8qJOEumbQQwyHvQHecSBoFh1ndtWjb1JKSVXOPA/edit#gid=0")
g_data$col_a <- as.character(g_data$col_a)
g_data
```

3. The proceeding $ symbol has been dropped from rows 4 through 13. The data now looks like this

| col_a |
| :-- |
| "48000" |
| "40000"" |
| "NULL" |
| "15000"" |
| "41715" |
| "20857"" |
| "10429" |
| "52143"" |
| "26072" |
| "41714"" |
| "78215" |
| "51000"" |
| "50000" |
| "$15,643-26,072" |

**Comment by nviraj** [comment]
@charliejhadley, I ran into something similar where it looks like auto guessing column types is a bit buggy even when you increase the number of rows used to guess column types (g_data and g_data_guess_max result in same data). 

In your case, by the time you convert it to a character column, it's already too late. What you could do, is specify the column type explicitly while reading the sheet. This will pull the data exactly the way you want it to. Refer to "g_data_explicit" section in the below Reprex.

``` r
library(googlesheets4)

# Sheet location
sheet_url <- "https://docs.google.com/spreadsheets/d/1IA3q8qJOEumbQQwyHvQHecSBoFh1ndtWjb1JKSVXOPA/edit#gid=0"

# Reading google sheet with default parameters
g_data <- googlesheets4::read_sheet(
  sheet_url
)
#> ! Using an auto-discovered, cached token.
#>   To suppress this message, modify your code or options to clearly consent to
#>   the use of a cached token.
#>   See gargle's "Non-interactive auth" vignette for more details:
#>   <https://gargle.r-lib.org/articles/non-interactive-auth.html>
#> i The googlesheets4 package is using a cached token for 'viraj@miqdigital.com'.
#> v Reading from "foo".
#> v Range 'Sheet1'.

# Unexpected data where format is lost
str(g_data)
#> tibble [14 x 1] (S3: tbl_df/tbl/data.frame)
#>  $ col_a:List of 14
#>   ..$ : num 48000
#>   ..$ : num 40000
#>   ..$ : NULL
#>   ..$ : num 15000
#>   ..$ : num 41715
#>   ..$ : num 20857
#>   ..$ : num 10429
#>   ..$ : num 52143
#>   ..$ : num 26072
#>   ..$ : num 41714
#>   ..$ : num 78215
#>   ..$ : num 51000
#>   ..$ : num 50000
#>   ..$ : chr "$15,643-26,072"

# Increase number of rows used to guess col types to see if it will make a change
g_data_guess_max <- googlesheets4::read_sheet(
  sheet_url,
  guess_max = 1000
)
#> v Reading from "foo".
#> v Range 'Sheet1'.

# Looks like it's a majority wins kind of a situation when guessing column types rather than it being influenced by outliers
str(g_data_guess_max)
#> tibble [14 x 1] (S3: tbl_df/tbl/data.frame)
#>  $ col_a:List of 14
#>   ..$ : num 48000
#>   ..$ : num 40000
#>   ..$ : NULL
#>   ..$ : num 15000
#>   ..$ : num 41715
#>   ..$ : num 20857
#>   ..$ : num 10429
#>   ..$ : num 52143
#>   ..$ : num 26072
#>   ..$ : num 41714
#>   ..$ : num 78215
#>   ..$ : num 51000
#>   ..$ : num 50000
#>   ..$ : chr "$15,643-26,072"

# Explicitly mention column type (readr style)
g_data_explicit <-
  googlesheets4::read_sheet(
    sheet_url,
    col_types = "c"
  )
#> v Reading from "foo".
#> v Range 'Sheet1'.

# Works better, if you have multiple columns and you want all of them to be read as character this will still work because col_types is recycled
str(g_data_explicit)
#> tibble [14 x 1] (S3: tbl_df/tbl/data.frame)
#>  $ col_a: chr [1:14] "48000" "40000" NA "$15,000" ...
g_data_explicit
#> # A tibble: 14 x 1
#>    col_a         
#>    <chr>         
#>  1 48000         
#>  2 40000         
#>  3 <NA>          
#>  4 $15,000       
#>  5 $41,715       
#>  6 $20,857       
#>  7 $10,429       
#>  8 $52,143       
#>  9 $26,072       
#> 10 $41,714       
#> 11 $78,215       
#> 12 51,000        
#> 13 $50,000       
#> 14 $15,643-26,072
```

<sup>Created on 2022-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
I would say that googlesheets4 is working as intended and as documented here. (I disagree with "looks like auto guessing column types is a bit buggy", but I'm board with most of what @nviraj says above.)

Most -- but not all! -- of these cells are numeric. The dollar signs, commas, etc. come from formatting doesn't influence the underlying data, just what's shown to human eyeballs in the browser. But then there's a text cell at the very end! In these "mixed types" situations, googlesheets4 always guesses the `List` column type:

> `List`, as in "list-column". Each cell is a length-1 atomic vector of its discovered type.

Explicitly requesting a `"character"` column is the intended way to do what you want here @charliejhadley. You get a better result by telling googlesheets4 to parse the cells as `"character"` than giving googlesheets4 no type guidance and coercing to character after-the-fact.

Sidebar: I am working on levelling up column specification for googlesheets4 (making it more like readr/vroom), so it will become easier in the future to express that you want a default column type of `"character"`.
