### ISSUE TITLE
Issue with getting the address to the new spreadsheet

### ISSUE THREAD

**Issue by dokato** [tidyverse/googlesheets4#252]
I'm trying to get the address of my newly created spreadsheet, but I get this error:

```r
> a = gs4_create("C_report")
Creating new Sheet: "C_report"
> a
Error in with_abort(gs4_get(x)) : could not find function "with_abort"
```

Expected behaviour: link to the spreadsheet.

```r
> packageVersion("googlesheets4")
[1] ‘0.3.0’
```

```
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.0                         
year           2021 
```

**Comment by dokato** [comment]
For context: the reason why I need it, is that I want to dynamically create a link to the spreadsheet in a markdown report.

**Comment by cpilat97** [comment]
Are you tied to googlesheets4 version 0.3.0 or can you update? The official version on CRAN is 1.0.0, it's possible with a package update might be needed.

**Comment by dokato** [comment]
Thanks @cpilat97 , indeed the new version of the package fixed the problem.
