### ISSUE TITLE
read_sheet pulls partially loaded sheet

### ISSUE THREAD

**Issue by montessoriforall** [tidyverse/googlesheets4#258]
Hi all:

I want to `read_sheet` one sheet from a Google Spreadsheet that makes multiple IMPORTRANGE and VLOOKUP calls. However, `read_sheet` sometimes pulls the sheet while it is still "Loading..." (not completely loaded, usually just the first few rows), as below:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/93950156/170341340-2d13e7d0-7da5-4810-abc5-3bd75ac622de.png">

I can't include this sheet because it's confidential information. I don't have a reproducible example on hand yet, though I will try to create one today.

I'm assuming that the problem is that either IMPORTRANGE, VLOOKUP, or the combination of the two loads on Google's end too slowly and read_sheet simply reads the top few rows.

**Comment by jennybc** [comment]
I am not aware of any facilities in the Sheets API for dealing with such a problem, but if you discover something the R package could take advantage of, I'd be happy to take a look.

In a very generic sense, `Sys.sleep()` is one way we can delay an operation in R. It's crude, but often that is enough to allow some remote system to "catch up" before we do something.
