### ISSUE TITLE
Unable to write data on google sheets

### ISSUE THREAD

**Issue by finance-data** [tidyverse/googlesheets4#261]
I have a SQL query which takes 1-2 minutes to run but while running a R-script to populate google sheet, it takes a lot of time and at end it gives a error.

✔ Editing "ASP Level KPI's".
✔ Writing to sheet 'Auction Dump'.
Error in `gargle_abort_request_failed()`:
! Server error: (500) INTERNAL
• Internal server error. Typically a server bug.
• Internal error encountered.
Backtrace:
    ▆
 1. └─googlesheets4::range_write(...)
 2.   └─gargle::response_process(resp_raw)
 3.     └─gargle:::gargle_abort_request_failed(error_message(resp), resp)
 4.       └─gargle:::gargle_abort(...)
 5.         └─cli::cli_abort(...)
 6.           └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Execution halted

Any idea on what is the issue?

**Comment by jennybc** [comment]
Errors with code 500 or higher are, as advertised, errors on the server side. And this one is extremely non-specific. Is it repeatable or intermittent? What's the relevance of your SQL query here?

**Comment by jennybc** [comment]
What I'm saying is that this is very likely not something that can be addressed / fixed by the googlesheets4 package.
