### ISSUE TITLE
`gs4_auth` is now defaulting to OAuth instead of using a Service Account json

### ISSUE THREAD

**Issue by yogat3ch** [tidyverse/googlesheets4#262]
Hi @jennybc,
Thank you for this pervasively useful package!
I'm not sure how I would include a reprex since this is related to behavior when using a service account json.

`gs4_auth` used to silently authenticate with a Service Account json when the path was passed to the `path` argument as follows:
```r
googlesheets4::gs4_auth(path = "[path to service account json]")
```
However, 
In recent updates to `googlesheets4` or perhaps the underlying `gargle` functionality, the Service Account JSON is no longer being recognized and `gs4_auth` is now displaying the "Waiting for authentication in browser" message and opening the OAuth dialog in the browser.

Any ideas on what has changed and why SA JSON authentication is now failing?

**Comment by jennybc** [comment]
This probably means that the service account token has become invalid or gone missing. I don't think it's a change in googlesheets4 or gargle, I think it's a change in your world.

Some troubleshooting ideas:
https://gargle.r-lib.org/articles/troubleshooting.html

**Comment by yogat3ch** [comment]
Hi @jennybc,
Third time's the charm I guess?
I deleted all the keys and recreated a new key and now it appears to be working again 🤷
Maybe I accidentally modified the other JSON somehow?

Anyway, thanks for your time and attention 🙏
