### ISSUE TITLE
Cannot authenticate "Something went wrong"

### ISSUE THREAD

**Issue by Deleetdk** [tidyverse/googlesheets4#272]
I reinstalled to Mint 21 (Ubuntu 22.04 based) from Mint 19.3 (Ubuntu 20.04 based), and I can no longer use **googlesheets4** due to authentication problem. It opens the browser as normal, but when clicking, Google just says "something went wrong". I've tried a few times without luck.

![something went wrong](https://user-images.githubusercontent.com/6759913/196884739-58349c7a-4b26-4b7e-9285-379acffc2b68.png)

```r
library(googlesheets4)
gs4_auth("youremail@gmail.com")
```

The video shows the process though nothing unusual happens.

[gs4_author_error-2022-10-20_09.26.25.mkv.zip](https://github.com/tidyverse/googlesheets4/files/9827375/gs4_author_error-2022-10-20_09.26.25.mkv.zip)

**Comment by jennybc** [comment]
I am deeply skeptical that this is something within the purview of googlesheets4. It's more likely to be a Google problem (they were having server issues) or a local config problem. If I google `sign in with google "something went wrong"`, there are lots of hits and my suggestion is to read / work through some of those.

**Comment by Deleetdk** [comment]
I tried cleaning cookies and site data. Didn't work. However, I tried in Chrome instead of Firefox, and it worked. So it is something with Firefox or some extension.
