### ISSUE TITLE
to skip comment line

### ISSUE THREAD

**Issue by sterding** [tidyverse/googlesheets4#277]
It would be great to have a similar function as read.table() to skip the comments line in the Google spreadsheet. 
e.g. comment.char = "#"

**Comment by jennybc** [comment]
There is a `skip` parameter, but that is just a number. I have never perceived this to be terribly common in spreadsheets, i.e. it feels much more likely to come up in a plain text file, such as what `read.table()` takes as input. And spreadsheets support various range-based methods of targetting specific cells. So, I get it, but this is definitely lower priority than some other missing features.

**Comment by jennybc** [comment]
Closing since this is not on the roadmap at present.
