### ISSUE TITLE
Documentation request: Is gs4_deauth the opposite of gs4_auth?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/googlesheets4#278]
A companion issue to https://github.com/tidyverse/googledrive/issues/412, with the same description, _mutatis mutandis_ `googledrive::drive_auth()`/`googledrive::drive_deauth()` ↔️ `googlesheets4::gs4_auth()`/`googlesheets4::gs4_deauth()`.

**Comment by jennybc** [comment]
I've just re-read this cluster of issues and I still feel as I did when I closed the bigrquery issue. I'm OK with the docs as they are. I think this pair of functions just doesn't do what you were hoping it did.
