### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by pachamaltese** [tidyverse/googlesheets4#28]
Dear Dr. Bryan

I it was suggested [here](https://twitter.com/JennyBryan/status/1146813853193293824) I am opening an issue to ask how to contribute to improve this package in any way, so that it can reach a [stable lifecycle](https://www.tidyverse.org/lifecycle/#stable), and so that it can be on CRAN.

I can start by solving some of the issues from this repository and send PRs accordingly, as long as we can coordinate what to do so that we do not reinvent the wheel w.r. to a problem.

Best regards,

**Comment by jennybc** [comment]
General guidance re: contributing added in b56a46ccff4c25f539104c2db597af7b8395f552. I'm moving towards an initial CRAN release very soon (#34).
