### ISSUE TITLE
 range_speedread request failed [429] -> too many calls?

### ISSUE THREAD

**Issue by HugoGit39** [tidyverse/googlesheets4#302]
Hi

I just tested the ` range_speedread` function where I called it like 5 times close to each other (within a minute). I received a Request failed [429]. error...how come?

As I understand this is request is not called via the API right? So calls should be unlimited? Or how do I see this?

Moreover, my plan is to use it with a lot of users in a Shiny app (way more than 300 calls per minute which Google now limits per minute). Solution is to pay for more calls? Or is ` range_speedread`  not really convinient for this?

**Comment by jennybc** [comment]
My memory of `range_speedread()` is a big foggy now, but even in the docs I see this:

> Note that the Sheets API is still used to retrieve metadata on the target Sheet, in order to support range specification. `range_speedread()` also sends an auth token with the request, unless a previous call to [`gs4_deauth()`](https://googlesheets4.tidyverse.org/reference/gs4_deauth.html) has put googlesheets4 into a de-authorized state.

So I suspect it's these API calls that are biting you. It sounds possible that you should read the source of `range_speedread()` and build the URL you need with your bare hands.

**Comment by jennybc** [comment]
I am loath to offer Shiny-specific advice, but yes it definitely makes sense to arrange your app's logic to only read the data anew as often as you think it could be changing.

I think if you're really worried about quota you should cut the Sheets API out of the story altogether and use the special URL that's formed inside `range_speedread()` to get the data, in csv form, from a normal HTTP call.

**Comment by HugoGit39** [comment]
How do i do this?

> use the special URL that's formed inside range_speedread() to get the data, in csv form, from a normal HTTP call.

**Comment by jennybc** [comment]
You could look at the source of `range_speedread()`?

I think we've now reached "let me StackOverflow that for you". Here's a post on forming a URL for downloading Google Sheets as csv:

https://stackoverflow.com/a/64778214
