### ISSUE TITLE
Optionally import empty cells

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/googlesheets4#4]
https://github.com/tidyverse/googlesheets4/blob/5b97156d3bce2fa0d25a5bc8beb11a95eaa6d358/R/sheets_cells.R#L107-L110

It's exciting to see this take shape!

Empty, formatted cells have a lot of utility when unpivoting pivot tables or decoding formatting-as-data.  For example, legends often have the formatting and the code in separate cells, so the formatted cell is empty.

Are there good reasons not to import them at all?  (I accept that importing them by default could be confusing)

**Comment by jennybc** [comment]
I will push a bunch of work soon. `sheets_cells()` is meant to be a low-level-but-user-facing function, for people like you, who might want to build things on top. So I definitely want to get `sheets_cells()` right. Once I push, let's discuss further about what is missing and how to provide access. Right now it's very much shaped by what I need, probably too much.

**Comment by jennybc** [comment]
I'm ready to talk about this now. When you're ready, would you create a Sheet with features that would allow us to talk concretely about the benefits of returning empty cells?

**Comment by nacnudus** [comment]
The response to this appeal wasn't overwhelming.  Build it and they will come? :grimacing: 

![tweet](https://user-images.githubusercontent.com/3522552/40455847-95b0f0da-5ee6-11e8-9d3e-934175292f56.png)

But anyway, here's a [googlesheet](https://docs.google.com/spreadsheets/d/1UbdlyITXLvsxQt6kpszu5gfiDmF5Q-wOrNC7l4E9jOg/edit#gid=0) to demonstrate use cases.

The "legend" tab uses fill colour to encode the species.  The legend unhelpfully doesn't combine text and fill colour in the same cell.  Unless the empty, coloured cells are imported, this information is lost.

![legend](https://user-images.githubusercontent.com/3522552/40455939-f49d4cba-5ee6-11e8-87d7-974e9712f777.png)

The "anchor" tab uses a border to mark the bottom of a table, before a footnote.  The border is applied to the top of the empty cell below the table, rather than to the bottom of the data cell at the bottom of the table.

![anchor](https://user-images.githubusercontent.com/3522552/40455941-f6e0dab4-5ee6-11e8-831e-c39719aa5fd1.png)

The "comment" tab has a comment on an empty cell.

![comment](https://user-images.githubusercontent.com/3522552/40456502-a0fab194-5ee9-11e8-9e63-022eb55ce330.png)

I can't get `reprex()` to work because of problems authenticating its session, but this code should show that the border marking the bottom of the table in sheet `anchor` is applied to top of the empty cell `A5`, rather than to the bottom of the data cell `A4`, and also that the empty cells, colours, borders and comments can be imported by tidyxl after exporting to xlsx.

```r
library(googledrive)
library(googlesheets4)
library(tidyxl)
library(here)

# Download the spreadsheets natively and in xlsx format
gs_legend <- sheets_cells("1UbdlyITXLvsxQt6kpszu5gfiDmF5Q-wOrNC7l4E9jOg", sheet = "legend")
gs_anchor <- sheets_cells("1UbdlyITXLvsxQt6kpszu5gfiDmF5Q-wOrNC7l4E9jOg", sheet = "anchor")
gs_comment <- sheets_cells("1UbdlyITXLvsxQt6kpszu5gfiDmF5Q-wOrNC7l4E9jOg", sheet = "comment")
drive_download(file = "empty-formatted-cells", overwrite = TRUE)

# The empty cells of the legend are omitted
gs_legend

# The empty cell with the top border is ommitted
gs_anchor

# The empty cell with the comment is omitted
gs_comment

xl_cells <- xlsx_cells(here("empty-formatted-cells.xlsx"))
xl_formats <- xlsx_formats(here("empty-formatted-cells.xlsx"))

bottom_border <- xl_formats$local$border$bottom$style
top_border <- xl_formats$local$border$top$style

# No cell has a bottom border
dplyr::filter(xl_cells, sheet == "anchor", !is.na(bottom_border[local_format_id]))

# The cell with a top border is empty
dplyr::filter(xl_cells, sheet == "anchor", !is.na(top_border[local_format_id]))

# The empty cell with a comment is retrieved, and so is the comment
dplyr::filter(xl_cells, sheet == "comment")[, c("address", "comment")]
```

**Comment by nacnudus** [comment]
This came up again with an annual leave planning sheet (anonymised) 

https://docs.google.com/spreadsheets/d/1Zm3QzsRbrGZQCrmchHL47YO92yrNYHtfqLXyy2swN54/edit?usp=sharing

![image](https://user-images.githubusercontent.com/3522552/62065003-02622a80-b226-11e9-850f-86b0912fd032.png)

**Comment by jennybc** [comment]
So this is going to require changing which `fields` I retrieve, because right now, I truly have no data for those emtpy-but-formatted cells.

Am currently mulling over whether to expose `fields` in its full glory in `sheets_cells()` or if some higher-level argument should appear that says "give me format info" and googlesheets4 decides how to implement that via `fields`.

**Comment by jennybc** [comment]
Because I don't know where else to file this knowledge, I'll put it here.

There are 2 ways to annotate a cell:

  * Note via *Insert > Note*
  * Comment via *Insert > Comment*

I can see notes via the API but not comments. A note is part of the CellData schema. So it is now accessible via `sheets_cells()`.

I can't see the comment @nacnudus put in his demo sheet. Neither in the browser, nor via the API. I think you can access the comments *via the Drive API*.

Conclusion: if you want an annotation to be available in the Sheets-world, use a note.
