### ISSUE TITLE
sheets_read()/read_sheet fails on this dataset

### ISSUE THREAD

**Issue by BriBecker** [tidyverse/googlesheets4#55]
These functions fail on this test googlesheet [test googlesheet](https://docs.google.com/spreadsheets/d/1Dot2umxJinHyWwbq1a5wONARlUgJi9gnS8kRmRoa_nI/edit?usp=sharing).

E.g, 
```
df <- sheets_read(
  ss = 'https://docs.google.com/spreadsheets/d/1Dot2umxJinHyWwbq1a5wONARlUgJi9gnS8kRmRoa_nI/edit#gid=0'
)
```
throws 
```
Reading from 'Test Dataset'
Range "'Sheet1'"
Error: is_string(ctype) is not TRUE
```

I cloned the package and debugged to where the `parse` function is eventually called from the `make_column.R` file. 
`stopifnot(is_string(ctype))` is triggered since `ctype` is a list (rather than what I'd guess should be a character vector of length 1).

I thought maybe this was since the header was missing a value, but that does not appear to be the problem from interactively testing.

**Comment by jennybc** [comment]
I am able to read this.

``` r
library(googlesheets4)

sheets_deauth()

df <- sheets_read(
  ss = 'https://docs.google.com/spreadsheets/d/1Dot2umxJinHyWwbq1a5wONARlUgJi9gnS8kRmRoa_nI/edit#gid=0'
)
#> Reading from 'Test Dataset'
#> 
#> New names:
#> * `` -> ...4
df
#> # A tibble: 3 x 5
#>   `Assigned To` `Complete?` `Service Contract Updat… ...4  `New or Current`
#>   <chr>         <chr>       <chr>                    <chr> <chr>           
#> 1 Genna         X           X                        x     Current         
#> 2 Genna         X           X                        x     Current         
#> 3 Katie         X           X                        x     Current
```

<sup>Created on 2019-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

My first suggestion is that you update googlesheets4.

**Comment by rishi1984** [comment]
Hello Jenny..I am also facing the same issue.The version of googlesheets4 is 0.1.0.Please help
