### ISSUE TITLE
Problems connecting to GDrive

### ISSUE THREAD

**Issue by mssanjavickovic** [tidyverse/googlesheets4#58]
Getting this error with googlesheets4: Sign in with Google temporarily disabled for this app

Any insights? 

Thanks

Sanja

**Comment by jennybc** [comment]
A couple things are odd here:

  * "Problems connecting to GDrive": This package is wraps the Google **Sheets** API, not Drive.
  * I just authenticated with no problems using googlesheets4 (this package).

It is likely you are seeing a problem with an older package, googlesheets. And yes the default OAuth app no longer works, which is presumably related to Google shutting down the v3 API, which googlesheets wraps.

I advise that you transition your Sheets work, from R, to this package, googlesheets4 and googledrive.

If you need to keep using googlesheets for a while, see this thread about getting your own oauth app:

https://github.com/jennybc/googlesheets/issues/397

Again, most importantly: the v3 Sheets API and the original googlesheets package is going to stop working entirely in March 2020:
