### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by alex-steiner-next** [tidyverse/googlesheets4#63]
I am getting an error authenticating my account with the error:

Sign in with Google temporarily disabled for this app

**Comment by kaveh1000** [comment]
Alex, are you using the old googlesheets or the new googlesheets4? I get exactly what you are getting with the original (which was ok before). I then moved to 4, but now I get this problem that I reported 2 days ago:

https://github.com/tidyverse/googlesheets4/issues/62

Love to get a solution!

**Comment by invertdna** [comment]
Same issue here!

**Comment by jennybc** [comment]
@alex-steiner-next and @invertdna please show me your exact R session -- such that it reveals the loaded packages and versions. I strongly suspect you are using the original package (googlesheets) and not this package, its successor, googlesheets4 (<-- note the 4!). And that what you are experiencing is this:

https://github.com/jennybc/googlesheets/issues/397

`sessionInfo()`, `devtools::session_info()`, and `packageVersion()` should all help you reveal this info.

**Comment by invertdna** [comment]
Apologies. I HAD loaded googlesheets4, but had missed the associated changes in syntax, AND had first loaded googlesheets. So, hence the error... it was simply running the original code w googlesheets, rather than googlesheets4.  I can now get authenticated.

**Comment by jennybc** [comment]
Ok thanks. I think we can close this.

**Comment by alex-steiner-next** [comment]
Yes, sorry I was still using the functions from googlesheets, once I changed over, everything was fine
