### ISSUE TITLE
[FR] sheets_clear() and sheets_write()

### ISSUE THREAD

**Issue by ben519** [tidyverse/googlesheets4#67]
Hi Jenny, here's my feature request for version-1 `sheets_clear() ` and `sheets_write()` functions.

# sheets_clear()
```
sheets_clear <- function(ss, sheet = NULL, range = NULL){
  ### How it works:
  # This method clears the contents of a range
  # 'ss' must identify an existing google sheet
  # 'sheet' identifies a worksheet, just as in sheets_read()
  # 'range' (optional) identifies a range of cells to be cleared, just as in sheets_read(). 
  #  If not given, the whole worksheet will be cleared.
  
  # ...
}
```

# sheets_write()
```
sheets_write <- function(ss = NULL, df, sheet = NULL, top_left_row = 1, top_left_col = 1, top_left_range = NULL, 
                         row_names = FALSE, col_names = TRUE, with_filter = TRUE){
  
  ### How it works:
  # This method does one of two things. If 'ss' is NULL, it creates a new google sheet and adds data to it.
  # Otherwise, it overwrites/adds the data to an existing google sheet.
  # 'df' should be a data.frame we want to slap onto some google sheet
  # 'sheet' identifies a worksheet, just as in sheets_read()
  # The location of the data we're putting on the sheet is given by either
  #  1. a combination of 'top_left_row' and 'top_left_col' or
  #  2. 'top_left_range'. (The top left cell of the given range will be used. If the range contains > 1 cell, 
  #     warn the user)
  # 'row_names' and 'col_names' determine whether to include row and col names
  # 'with_filter' determines whether to apply row filters to the top row of the newly added data
  
}
```

# Notes
- [openxlsx::writeData()](https://github.com/awalker89/openxlsx/blob/master/R/writeData.R) writes data to an excel worksheet, and it's fairly good at its job. It's worth reviewing.
- My `sheets_write()` function can only write one dataframe at a time. I had an obvious desire to generalize this into a named list that could write multiple dataframes, but I **strongly** suggest avoiding this complexity (for now) and focus on writing one dataframe to a sheet.
- I'm assuming NAs will be written as empty strings or however Google Sheets treats missing data
- Not sure the best way to handle Inf and -Inf. Perhaps use the largest value Google Sheets supports
- I haven't even tried to figure out an interface for applying formats. This is important, but I still see it as a v2 kind of thing. 
- Adding hyperlinks to text is something I do a lot, but I also see it as a v2 item.
- I don't mess with named ranges much, but I'm sure some people do. Updating a named range might require different functionality, and may be better suited for a separate function
- `sheets_clear()` is important because, suppose you have a worksheet with a table of 10 rows and you want to update it in a way that reduces it to 8 rows. `sheets_write()` by itself cannot do that. You need to make successive calls, `sheets_clear()` >> `sheets_write()`. Maybe some won't like it, but I think this design is fine (Separation of Concerns, Modularity, ... and all that)

Cheers

**Comment by rosieabe** [comment]
I have a need to edit specific cell ranges in some of my scripts, and if some expanded write/edit functionality could be added to `googlesheets4`'s newly added `write_sheet()` function, I would be able to fully transition from using `googlesheets` to using `googlesheets4` ahead of the deprecation of the Sheets v3 API.

I have previously used code like the below in order to update cells, so if there is some way to handle this kind of case with the next version of `write_sheet()`, I would be very grateful.

old, `googlesheets` function: 

`
gs_edit_cells(my_sheet, 
                       ws = "some_sheet",
                       input =  update_tbl,
                       anchor = 'A10',
                       col_names = FALSE)
`

I do not have a great sense of the best way to implement this, but I found this feature request and thought I'd add my specific use case in case it is helpful.

Thank you!

**Comment by jennybc** [comment]
More targeted writing is on the way @rosieabe. I understand that this is basically the largest remaining obstacle for people switching from googlesheets to googlesheets4 and it's my top priority now that rstudio::conf is over.

**Comment by jennybc** [comment]
I opened #109 for `sheets_clear()` and `sheets_edit()` just got merged. `sheets_write()` and `sheets_create()` have also been added since this issue was opened.
