### ISSUE TITLE
Accessing data from multi-sheet GoogleSheets

### ISSUE THREAD

**Issue by GitHubDoug** [tidyverse/googlesheets4#68]
---
For my classes I set up GoogleSheets with:
i) A meta-data catalog describing sample or treatment data
ii) a data sheet, where students enter data for the different samples.

I am attempting to use googlesheets4 to directly import the catalog + data into R (rather than exporting from GoogleSheets as a .csv, downloading, and re-importing).
This fails because there are 2 sheets in the underlying googlesheet.
I may be simply ignorant of how to get to the underlying sheets after the 'sheets_get' function.

```r
 https://docs.google.com/spreadsheets/d/1pT6-Rt1pKPO537cLzP3TQ3ePmVgSpPU2Hw_qg4v2g80/edit?usp=sharing

drive_find(n_max = 30)
Winogradsky <- sheets_get("1pT6-Rt1pKPO537cLzP3TQ3ePmVgSpPU2Hw_qg4v2g80")
voltages <- read_sheet(Winogradsky)
```

**Comment by jennybc** [comment]
Use the `sheet` argument to `read_sheet()` to access the (work)sheets by name or position.

**Comment by GitHubDoug** [comment]
Thanks
