### ISSUE TITLE
Finalize class naming scheme

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#71]
Currently there are ~3 types of S3 classes in this package. I want to review / affirm the class naming scheme for two types of classes:

  1. User-facing
  1. Derived from the the API spec

The remaining classes are internal and are working fine / names are fine. This includes all the cell and col types (e.g. `CELL_BLANK`, `CELL_NUMERIC`, `COL_LIST`) and `range_spec`.

### User-facing classes:

  * `sheets_id` holds the file ID of a Sheet. It's a string with classes `sheets_id` and `drive_id`, so it will work as the file identifier in a whole host of googlesheets4 and googledrive functions.
  * `sheets_Spreadsheet` holds metadata on a Sheet, including the file ID but also info about the (work)sheets and named ranges inside it. It is a heavily wrangled version of the [`Spreadsheet` schema](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#Spreadsheet).

``` r
devtools::load_all("~/rrr/googlesheets4")  
#> Loading googlesheets4

sheets_example("deaths")
#> [1] "1tuYKzSbLukDLe5ymf_ZKdQA8SfOyeMM7rmf6D6NJpxg"
#> attr(,"class")
#> [1] "sheets_id" "drive_id"

x <- sheets_example("deaths") %>% sheets_get()
class(x)
#> [1] "sheets_Spreadsheet" "list"
x
#>   Spreadsheet name: deaths
#>                 ID: 1tuYKzSbLukDLe5ymf_ZKdQA8SfOyeMM7rmf6D6NJpxg
#>             Locale: en
#>          Time zone: America/Los_Angeles
#>        # of sheets: 2
#> 
#> (Sheet name): (Nominal extent in rows x columns)
#>         arts: 1000 x 26
#>        other: 1000 x 26
#> 
#> (Named range): (A1 range)    
#>     arts_data: 'arts'!A5:F15 
#>    other_data: 'other'!A5:F15
str1(x)
#> List of 7
#>  $ spreadsheet_id : chr "1tuYKzSbLukDLe5ymf_ZKdQA8SfOyeMM7rmf6D6NJpxg"
#>  $ spreadsheet_url: chr "https://docs.google.com/spreadsheets/d/1tuYKzSbLukDLe5ymf_ZKdQA8SfOyeMM7rmf6D6NJpxg/edit"
#>  $ name           : chr "deaths"
#>  $ locale         : chr "en"
#>  $ time_zone      : chr "America/Los_Angeles"
#>  $ sheets         :Classes 'tbl_df', 'tbl' and 'data.frame': 2 obs. of  8 variables:
#>  $ named_ranges   :Classes 'tbl_df', 'tbl' and 'data.frame': 2 obs. of  10 variables:
#>  - attr(*, "class")= chr [1:2] "sheets_Spreadsheet" "list"
```

<sup>Created on 2019-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I'm not sure I like the `sheets_Spreadsheet` class name, i.e. the mixed casing and perhaps `Spreadsheet` itself (although it is connected to the `Spreadsheet` schema). It's conceivable that other schemas could get similar treatment later, so we have to think about how this pattern scales.

### Sheets v4 schemas

There are ~200 of these and I need to be able to create and parse many of them (though no where near all 200). These are internal classes.

  * `data-raw/discovery-doc-prep.R` causes selected schemas to be rectangled and stored in the internal `.tidy_schemas` object. When a schema becomes relevant to me, I add it here.
  * The functions in [schemas.R](https://github.com/tidyverse/googlesheets4/blob/master/R/schemas.R) make it easy to instantiate these classes, with some light validation, via generics `new()` and `patch()`.
  * Instances of these types have a class vector identifying the specific schema, declaring that it is a schema, and `list` (to make `jsonlite::toJSON()` happy).

``` r
devtools::load_all("~/rrr/googlesheets4")
#> Loading googlesheets4
class(new("Spreadsheet"))
#> [1] "googlesheets4_Spreadsheet" "googlesheets4_schema"     
#> [3] "list"
class(new("Sheet"))
#> [1] "googlesheets4_Sheet"  "googlesheets4_schema" "list"
class(new("GridRange"))
#> [1] "googlesheets4_GridRange" "googlesheets4_schema"   
#> [3] "list"
```

<sup>Created on 2019-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Things to think about: confirm I want to use `sheets_*` for the user-facing classes and `googlesheets4_*` for internal schema-based classes. The relationship between a schema's user facing class (e.g. `sheets_Spreadsheet`) and its internal class (`googlesheets4_Spreadsheet`).

**Comment by behrman** [comment]
I agree with your mixed feelings about mixed casing. One way to follow the tidyverse style guide could be to convert the internal classes to follow the guide, `googlesheets4_spreadsheet`, `googlesheets4_sheet`, `googlesheets4_grid_range`, and have the user-facing classes simply substitute `sheets_`.

**Comment by jennybc** [comment]
I think the user-facing classes are probably the better candidate for getting snake case / tidy verse style. It ties into another issue I need to address soon, holistically, which camelCase vs snake_case of functions arguments that I pass through to the API. I just need to apply some existing smarts from googledrive and bigrquery. 

So the user-facing classes could keep their `sheets_` prefix, consistent with the function naming scheme and honour tidyverse snake_case style.

It makes sense for the internal classes that map onto the schemas to honour the exact names used by the API. It just makes my life easier. But a shorter prefix, such as `gs4_`, would probably be an improvement.

**Comment by behrman** [comment]
I think your suggestions are a fine solution. Keep the user-facing interface snake_case / tidyverse style wherever possible, and use whatever works best for you internally.

**Comment by jennybc** [comment]
Decision reached with @Hadley:

Any user facing class that is related to a schema should be named like `googlesheets4_schema`. Use the `googlesheets4_` prefix instead of `sheets_` and put the schema name into lower_snake_case. So `sheets_Spreadsheet` becomes `googlesheets4_spreadsheet`.

The internal schema-derived classes should be like `googlesheets4_schema_SchemaName` / `googlesheets4_schema` / `list`. Use the ``googlesheets4_schema` prefix and retain the API's UpperCamelCase.
