### ISSUE TITLE
Worksheets

### ISSUE THREAD

**Issue by somnambWl** [tidyverse/googlesheets4#72]
Hello,

is there any estimated date when creating worksheets will be possible? The docs still reads 

> But, if you need more granular control, such as writing to specific worksheets or cells, that requires the Sheets API. This is not yet implemented in googlesheets4, but will be

and I haven't find it yet, so I am asking.

**Comment by jennybc** [comment]
I have draft versions of `sheets_create()` and `sheets_write()` already and am working on this very actively. Those early versions are only writing character data atm, because I'm working on the interface around *where* to write first.

I plan to invite users to beta test writing before Christmas.
