### ISSUE TITLE
`na` argument ignored in read_sheet

### ISSUE THREAD

**Issue by antoine-sachet** [tidyverse/googlesheets4#73]
Specifying custom NA values in a non-character column does not work: the NA values are treated as character cells instead of being set to NA. 

This is related to other opened issues about a better column type interface (#51 and in particular #64), but it is a sufficiently distinct use case to warrant a separate issue IMO. 

I have created a public spreadsheet (`1D98U_4wx2pm2-0hUuOOJNM0NKDv-WouP2IRuBFnWrRg`) containing:

A | B | C | D
-- | -- | -- | --
1 | 1 | 1 | 1
Missing | NA |   | 2
3 | 3 | 3 | 3

Reprex:

``` r
googlesheets4::read_sheet("1D98U_4wx2pm2-0hUuOOJNM0NKDv-WouP2IRuBFnWrRg", 
    na = c("", "NA", "Missing"))
#> Reading from 'Reprex for guessed ctype in presence of NAs'
#> 
#> # A tibble: 3 x 4
#>   A         B             C     D
#>   <list>    <list>    <dbl> <dbl>
#> 1 <dbl [1]> <dbl [1]>     1     1
#> 2 <chr [1]> <chr [1]>    NA     2
#> 3 <dbl [1]> <dbl [1]>     3     3
```

<sup>Created on 2019-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Of course, I was expecting the behaviour from `readr`.

``` r
  
csv_txt <- "A   B   C   D
1   1   1   1
Missing NA      2
3   3   3   3"

readr::read_delim(csv_txt, na = c("", "Missing", "NA"), delim = "\t")
#> # A tibble: 3 x 4
#>       A     B     C     D
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     1     1     1
#> 2    NA    NA    NA     2
#> 3     3     3     3     3
```

<sup>Created on 2019-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
I now see this

``` r
devtools::load_all()
#> Loading googlesheets4

ssid <- "1D98U_4wx2pm2-0hUuOOJNM0NKDv-WouP2IRuBFnWrRg"
sheets_browse(ssid)
read_sheet(ssid, na = c("", "NA", "Missing"))
#> Reading from 'Reprex for guessed ctype in presence of NAs'
#> 
#> # A tibble: 3 x 4
#>       A     B     C     D
#>   <dbl> <dbl> <dbl> <dbl>
#> 1     1     1     1     1
#> 2    NA    NA    NA     2
#> 3     3     3     3     3
```

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
