### ISSUE TITLE
Implement "second tier" (work)sheet operations

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#80]
The most important (work)sheet functions now exist:

  * ~`sheets_sheet_data()`~ `sheets_sheet_properties()` and `sheets_sheet_names()` give info about sheets
  * `sheets_sheet_add()` can add one or more sheets
  * `sheets_sheet_delete()` can delete one or more sheets
  * `sheets_write()` (and `sheets_create()`) can write data into sheets ~(albeit only character, but that will change soon)~

The next wave of slightly-less-important worksheet functions are:

  * [x] Rename
  * [x] Relocate, this and all above via [`UpdateSheetPropertiesRequest`](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#updatesheetpropertiesrequest).
  * [x] Duplicate via [`DuplicateSheetRequest`](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#duplicatesheetrequest). Send a one-off clump of 4 pcs of info.
  * [x] "Copy to" via [`copyTo` endpoint](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo)

Worksheet operations that are even lower priority, in terms of replacing existing functionality in googlesheets:
  * Hide
  * Protect

**Comment by jsstanley** [comment]
Thanks for all your hard work on this very useful package. 

Do you also have plans to implement a function to write to specific cells/ranges within sheets, similar to what gs_edit_cells() from the googlesheets package does?

**Comment by jennybc** [comment]
> Do you also have plans to implement a function to write to specific cells/ranges within sheets, similar to what gs_edit_cells() from the googlesheets package does?

Yes, for sure. I'm just working on "write a whole data frame to a sheet" first.

**Comment by jsstanley** [comment]
Makes sense, thanks again!

**Comment by martadziuba** [comment]
Thanks Jenny for your hard work. I second the need for a gs_edit_cells() equivalent.

**Comment by jennybc** [comment]
Done here for now. Willl do protect and hide once there is a convincing need.
