### ISSUE TITLE
Time zone for date times

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#82]
I am certain my current approach is too crude / inflexible, but it would help to hear how people push back in order to understand what would be most useful or expected.

**Comment by sjeangirard** [comment]
Hello Jenny,

Thank you for your work!

I am currently facing the issue where a DateTime with a non-GMT timezone will be modified to the value with the GMT timezone when writing to a google sheet

For example:
```R
library(googledrive)
library(googlesheets4)
library(lubridate)

sheets_deauth()

ss <- sheets_create()

tt <- with_tz(Sys.time(), tzone = "Pacific/Auckland")
print(tt)

write_sheet(tibble(Datetime=tt), ss, sheet=1)
drive_share(ss, role = "writer", type = "anyone")
sheets_browse(ss)

df_gsheet <- read_sheet(ss, sheet=1)
print(df_gsheet)

drive_trash(ss)
```

Should write 2020-04-07 11:47:29 but instead will write 2020-04-06 23:47:29.
I tried to modify the spreadsheet timezone settings but it does not seem to affect the result.

Please let me know if there is a proper way to write DateTime with timezones. 
I am converting it to character so far to avoid conversion.

**Comment by jennybc** [comment]
Can you show me an actual reprex? The code above can't possibly run because you can't create a Sheet after `sheets_deauth()`. The reason I ask is that I'd like to see the output on your machine, which should reveal the Sheet's time zone, which makes it easier for me to try to replicate your experience and fiddle around.

Did you try setting the Sheet time zone at creation time? Here's one of the [official examples for `sheets_create()`](https://googlesheets4.tidyverse.org/reference/sheets_create.html#examples):

``` r
sheets_create(
    "sheets-create-demo-3",
    locale = "fr_FR",
    timeZone = "Europe/Paris"
  )
```

If you need help creating a reprex -- where I can see your exact code and output -- there's an article about it:

https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html

**Comment by sjeangirard** [comment]
Hello Jenny,

Here is the modified reprex following your suggestion:

``` r

# With timeZone set during creation
ss <- sheets_create(
  "sheets-create-demo",
  locale = "en_US",
  timeZone = "America/New_York"
)

tt <- with_tz(Sys.time(), tzone = "America/New_York")
print(tt)
#> [1] "2020-04-15 06:07:18 EDT"

write_sheet(tibble(Datetime=tt), ss, sheet=1)
#> Writing to "sheets-create-demo"
#> Writing to sheet "Sheet1"

df_gsheet <- read_sheet(ss, sheet=1)
#> Reading from "sheets-create-demo"
#> Range "'Sheet1'"
print(df_gsheet)
#> # A tibble: 1 x 1
#>   Datetime           
#>   <dttm>             
#> 1 2020-04-15 10:07:18

# Without timeZone set during creation
ss_2 <- sheets_create(
  "sheets-create-demo_2"
)

tt <- with_tz(Sys.time(), tzone = "America/New_York")
print(tt)
#> [1] "2020-04-15 06:07:21 EDT"

write_sheet(tibble(Datetime=tt), ss_2, sheet=1)
#> Writing to "sheets-create-demo_2"
#> Writing to sheet "Sheet1"

df_gsheet <- read_sheet(ss_2, sheet=1)
#> Reading from "sheets-create-demo_2"
#> Range "'Sheet1'"
print(df_gsheet)
#> # A tibble: 1 x 1
#>   Datetime           
#>   <dttm>             
#> 1 2020-04-15 10:07:21
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
Thanks @sjeangirard that's exactly what I needed. I'll improve this before the release.

**Comment by jennybc** [comment]
@sjeangirard I "solved" your problem by telling you that it can't really be solved.

This issue prompted me to write an article on datetimes (and to do the background research I needed to do to write it!).

I'm afraid, the time zone of a Sheet does not have nearly the influence that you are hoping for -- it's very different from how time zones work in R.

Please see the new article for advice on how you can hack around this if you really want to. But my advice is to make peace with seeing datetimes in UTC in your Sheets, if you possibly can.

The article won't show up until the pkgdown site gets rebuilt. I'll try to come back here once I can drop a link in.
