### ISSUE TITLE
Is sheets_sheet_data() a confusing name?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#89]
`sheets_sheet_data()` returns a tibble with one row per (work)sheet. Is that name confusing? Specifically, does it suggest that it will return the data **in** the sheet?

Should it be `sheets_sheet_meta()` or `sheets_sheet_get()`?

``` r
library(googlesheets4)

sheets_deauth()

sheets_example("deaths") %>% 
  sheets_sheet_data()
#> # A tibble: 2 x 8
#>   name  index         id type  visible grid_rows grid_columns data  
#>   <chr> <int>      <int> <chr> <lgl>       <int>        <int> <list>
#> 1 arts      0 1210215306 GRID  TRUE         1000           26 <NULL>
#> 2 other     1   28655153 GRID  TRUE         1000           26 <NULL>
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

*Note: I am already considering removing the `data` column from the above object. In any case, I either need to populate it or remove it. It's just a placeholder now while I decide.*

**Comment by nacnudus** [comment]
Based on the issue title alone, I came here to write that I thought it returned the data, and to suggest "meta", so that's +1 to `sheets_sheet_meta()`, which must be one of the most meta function names around.

**Comment by jennybc** [comment]
A name that makes a lot of sense in the context of the API schema is `sheets_sheet_properties()`.
