### ISSUE TITLE
No sheets_write() or sheets_create() ?

### ISSUE THREAD

**Issue by gloignon** [tidyverse/googlesheets4#91]
Using R 3.5.3 with the latest CRAN version of googlesheets4.

There does not seem to be a sheets_write() or sheets_create() function.

What am I missing?

![image](https://user-images.githubusercontent.com/12416756/72617314-b22b7180-3906-11ea-997d-46dcdfb4ffbd.png)

**Comment by jennybc** [comment]
> What am I missing?

That `sheets_write()` and `sheets_create()` are in the dev version, not yet in the CRAN version.
