### ISSUE TITLE
sheets_read() can't read a table if there are colored elements

### ISSUE THREAD

**Issue by 4marel** [tidyverse/googlesheets4#97]
Hi,
Today I run into a problem: sheets_read() can't get info from any of my tables.
I got error message: 
"Error: Properties not recognized for the 'SheetProperties' schema:
  * tabColorStyle"

The only solution for this was removing all colors from spreadsheet (background cells color, text color and color on the sheets panel - http://img.netpeak.ua/amarel/158092528048_kiss_11kb.jpg).

Is there another way to solve this? 
A few days ago sheets_read() was friendly to using colors in spreadsheets.

**Comment by jennybc** [comment]
Can you make such a Sheet readable by me? I have test Sheets with color, which I can read. So it sounds like there may be more to this. But until I have access to a problem Sheet, I can't investigate.

[How to create a googlesheets4 reprex](https://googlesheets4.tidyverse.org/articles/articles/googlesheets4-reprex.html)

**Comment by jperkel** [comment]
I have the same problem. I cannot share my sheet with you, but create a simple table, eg (as a CSV):

`fruit,weight,color`
`banana,1,yellow`
`orange,2,orange`
`plum,3,purple`
`lime,4,green`

I colored the 3rd column according to those colors, and it downloads just fine (using `drive_find` followed by `read_sheet`. 

However, if you color the tab indicator at the bottom (ie, where it says 'Sheet1' at the bottom of the page, click the down arrow, then change color) and try again, it fails with error: "Error: Properties not recognized for the 'SheetProperties' schema: * tabColorStyle"

**Comment by jennybc** [comment]
It turns out the Sheets v4 API actually changed and has started sending novel fields for certain objects. The `tabColorStyle` property of a sheet is one of these changes. I've updated the internal object that holds the API schemas.

You'll need to re-install the dev version of googlesheets4 and remember to **restart R**:

``` R
# install.packages("devtools")
devtools::install_github("tidyverse/googlesheets4")
```

**Comment by jperkel** [comment]
Thank you, @jennybc! And thank you for this package -- it's fantastic!

**Comment by UTexas80** [comment]
Thank you Jenny. Much appreciated.
