### ISSUE TITLE
sheets_write() stopped working

### ISSUE THREAD

**Issue by amir2cs** [tidyverse/googlesheets4#98]
Hello, I'm very new here.

I've been using the sheets_write() function for the past few weeks to automate a few of my dashboards in google sheets. However, this morning the process failed with an error which ended with 'tabColor.'  I'm sorry I do not have the full error.

Anyway, I reinstalled the package and the sheets_write function disappeared. I've installed the development version as well but no luck. 

I have no idea what happened. It was working fine till yesterday and today it just broke. Please help!

**Comment by jennybc** [comment]
This is another presentation of #97. The Sheets API suddenly changed and started sending data with some new fields. I fixed it yesterday (d4b496e0ba6c103fc73853a634e8c556d8827d9d). You'll need the development version and to **restart R**.
